metadata-files:
  - _core/metadata.yml
  
website:
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - section: "PSYC214"
        contents: PSYC214/*
      - section: "PSYC234"
        contents: PSYC234/*