metadata-files:
  - _core/metadata.yml
  
website:
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - section: "PSYC5141"
        contents: PSYC5141/*
      - section: "PSYC5242"
        contents: PSYC5242/*
        
format:
  html: 
    include-in-header:
      - text: |
          <script>window.onload = function() {document.getElementById("autocomplete-0-input").placeholder = "Search Year 2";};</script>
