project:
  type: website
  output-dir: docs

website:
  title: "Statistics for Psychologists"
  favicon: "Images/favicon.png"
  page-navigation: true
  back-to-top-navigation: true
  search: 
    type: textbox
  
  repo-url: https://github.com/lu-psy-r/
  #repo-actions: [edit, issue]
  
  navbar:
    #logo: "Images/icon.png"
    left:
      - text: Home
        href: https://lu-psy-r.github.io/
      - text: Year 1
        file: https://lu-psy-r.github.io/year1
      - text: Year 2
        file: https://lu-psy-r.github.io/year2
      - text: MSc
        file: https://lu-psy-r.github.io/MSc
      - text: And More...
        file: https://lu-psy-r.github.io/more

  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - section: "PSYC121"
        contents: PSYC121/*
      - section: "PSYC122"
        contents: PSYC122/*
          
  page-footer:
    left: "Website developed by Matthew Ivory"

format:
  html:
    theme: 
      - default
      - custom.scss
    #css: styles.css
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    toc: true
    include-in-header:
      - text: |
          <script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  
editor: source

validate-yaml: false