---
title: 2. Single-Factor Between-Participants ANOVA
subtitle: "Mark Hurlstone"
order: 3
---


# Lectures

Watch Lecture 1 Part 1 [here](https://lancaster.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=4955c29d-628a-490f-842a-b4dc0079e462)

Watch Lecture 1 Part 2 [here](https://lancaster.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=a658ab65-57e0-439b-819f-b4dc007ca18a)

Watch Lecture 1 Part 3 [here](https://lancaster.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=61590e8a-df27-4e58-aba5-b4dc00858cd7)

Watch Lecture 1 Part 4 [here](https://lancaster.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=14aee97b-5805-4978-ba37-b4dc008d3a12)

Download the Lecture 1 slides [here](data/Wk2/Week 2 Lecture 1 Between-Participants ANOVA [HANDOUT].pdf), [here](data/Wk2/Week 2 Lecture 1 Between-Participants ANOVA [BIG SLIDES].pdf) for a larger version, and [here](data/Wk2/Week 2 Lecture 1 Between-Participants ANOVA [LIVE].zip) for the live version.  

Watch Lecture 2 Part 1 [here](https://lancaster.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=ffa1ebef-cf1d-45c7-8389-b4dd016dbb95)

Watch Lecture 2 Part 2 [here](https://lancaster.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=a343ff57-08f7-4d90-9f04-b4dd016dc1bf)

Watch Lecture 2 Part 3 [here](https://lancaster.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=d56893df-408a-4a27-b6b6-b4dd016dc5ea)

Watch Lecture 2 Part 4 [here](https://lancaster.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=2cbe832c-a807-4cc0-89a5-b4dd016dca62)

Watch Lecture 2 Part 5 [here](https://lancaster.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=91458208-c624-4816-89d6-b4dd016dcf61)

Download the Lecture 2 slides [here](data/Wk2/Week 2 Lecture 2 Assumptions of ANOVA and Follow Up Procedures [HANDOUT].pdf), [here](data/Wk2/Week 2 Lecture 2 Assumptions of ANOVA and Follow Up Procedures [BIG SLIDES].pdf) for a larger version, and [here](data/Wk2/Week 2 Lecture 2 Assumptions of ANOVA and Follow Up Procedures [LIVE].zip) for the live version. 

# Practical
Coming soon!