<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistics for Psychologists - 2. Multiple Regression Including Categorical Predictors</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../PSYC234/Week3.html" rel="next">
<link href="../PSYC234/Week1.html" rel="prev">
<link href="../Images/favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>window.onload = function() {document.getElementById("autocomplete-0-input").placeholder = "Search Year 2";};</script>
<script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="https://lu-psy-r.github.io/essentials/index_24.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="https://lu-psy-r.github.io/">
    <span class="navbar-title">Statistics for Psychologists</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year1/index.html"> 
<span class="menu-text">Year 1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year2/index.html"> 
<span class="menu-text">Year 2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year3/index.html"> 
<span class="menu-text">Year 3</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/MSc/index.html"> 
<span class="menu-text">MSc</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/more/index.html"> 
<span class="menu-text">And More…</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../PSYC234/index.html">PSYC234</a></li><li class="breadcrumb-item"><a href="../PSYC234/Week2.html">2. Multiple Regression Including Categorical Predictors</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../PSYC214/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC214</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Measurement, Variance and Inferential Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. One-Factor Between-Participants ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Assumptions of ANOVA and Follow-Up Procedures</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. One-Factor Within-Participants ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Revision of One-Factor ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Introduction to Factorial Designs and Interactions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Two-Factor Between-Participants ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Two-Factor Mixed and Within-Participants ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Three-Factor ANOVA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../PSYC234/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC234</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Review of correlation, simple regression and demonstration of multiple regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">2. Multiple Regression Including Categorical Predictors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Multiple regression models that include interactions (moderated variables)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Mediation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Factor analysis &amp; the binomial test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Wilcoxon rank-sum test and Wilcoxon signed-rank test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Kruskal-Wallis test and Friedman’s ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Binary logistic regression models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Expanding on binary logistic regression</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#lecture" id="toc-lecture" class="nav-link active" data-scroll-target="#lecture">Lecture</a>
  <ul class="collapse">
  <li><a href="#materials" id="toc-materials" class="nav-link" data-scroll-target="#materials">Materials</a></li>
  <li><a href="#pre-lab-activity" id="toc-pre-lab-activity" class="nav-link" data-scroll-target="#pre-lab-activity">Pre-Lab Activity</a></li>
  <li><a href="#test-yourself" id="toc-test-yourself" class="nav-link" data-scroll-target="#test-yourself">Test Yourself</a></li>
  <li><a href="#week-12-multiple-regression-with-categorical-predictors" id="toc-week-12-multiple-regression-with-categorical-predictors" class="nav-link" data-scroll-target="#week-12-multiple-regression-with-categorical-predictors">Week 12: Multiple Regression with Categorical Predictors</a>
  <ul class="collapse">
  <li><a href="#import-the-data" id="toc-import-the-data" class="nav-link" data-scroll-target="#import-the-data">Import the Data</a></li>
  <li><a href="#tidy" id="toc-tidy" class="nav-link" data-scroll-target="#tidy">Tidy</a></li>
  <li><a href="#visualise" id="toc-visualise" class="nav-link" data-scroll-target="#visualise">Visualise</a></li>
  </ul></li>
  <li><a href="#understand" id="toc-understand" class="nav-link" data-scroll-target="#understand">Understand:</a>
  <ul class="collapse">
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model">Model</a></li>
  <li><a href="#transform-types-of-categorical-contrasts" id="toc-transform-types-of-categorical-contrasts" class="nav-link" data-scroll-target="#transform-types-of-categorical-contrasts">Transform: Types of Categorical Contrasts</a></li>
  <li><a href="#dummy-or-treatment-coding-scheme" id="toc-dummy-or-treatment-coding-scheme" class="nav-link" data-scroll-target="#dummy-or-treatment-coding-scheme">Dummy or Treatment Coding Scheme</a></li>
  <li><a href="#a-quick-check-of-model-diagnostics" id="toc-a-quick-check-of-model-diagnostics" class="nav-link" data-scroll-target="#a-quick-check-of-model-diagnostics">A Quick Check of Model Diagnostics</a></li>
  <li><a href="#sum-or-deviation-coding-schemes" id="toc-sum-or-deviation-coding-schemes" class="nav-link" data-scroll-target="#sum-or-deviation-coding-schemes">Sum or Deviation Coding Schemes</a></li>
  <li><a href="#unbalanced-binary-variables" id="toc-unbalanced-binary-variables" class="nav-link" data-scroll-target="#unbalanced-binary-variables">Unbalanced Binary Variables</a></li>
  <li><a href="#mean-centering-continuous-variables" id="toc-mean-centering-continuous-variables" class="nav-link" data-scroll-target="#mean-centering-continuous-variables">Mean Centering Continuous Variables</a></li>
  <li><a href="#standardising-variables" id="toc-standardising-variables" class="nav-link" data-scroll-target="#standardising-variables">Standardising Variables</a></li>
  <li><a href="#ordered-variables" id="toc-ordered-variables" class="nav-link" data-scroll-target="#ordered-variables">Ordered Variables?</a></li>
  <li><a href="#checking-model-assumptions-and-diagnostics" id="toc-checking-model-assumptions-and-diagnostics" class="nav-link" data-scroll-target="#checking-model-assumptions-and-diagnostics">Checking Model Assumptions and Diagnostics</a></li>
  </ul></li>
  <li><a href="#communicate" id="toc-communicate" class="nav-link" data-scroll-target="#communicate">Communicate:</a>
  <ul class="collapse">
  <li><a href="#descriptive-statistics" id="toc-descriptive-statistics" class="nav-link" data-scroll-target="#descriptive-statistics">Descriptive Statistics</a></li>
  <li><a href="#correlations-between-truly-continous-predictors" id="toc-correlations-between-truly-continous-predictors" class="nav-link" data-scroll-target="#correlations-between-truly-continous-predictors">Correlations between (truly) continous predictors</a></li>
  <li><a href="#inferential-statistics---model-coefficients-ses-t-values-and-p-values" id="toc-inferential-statistics---model-coefficients-ses-t-values-and-p-values" class="nav-link" data-scroll-target="#inferential-statistics---model-coefficients-ses-t-values-and-p-values">Inferential Statistics - Model Coefficients, SEs, <em>t</em>-values and <em>p</em> values</a></li>
  <li><a href="#reporting-text" id="toc-reporting-text" class="nav-link" data-scroll-target="#reporting-text">Reporting Text</a></li>
  <li><a href="#plotting-predictions" id="toc-plotting-predictions" class="nav-link" data-scroll-target="#plotting-predictions">Plotting predictions</a></li>
  </ul></li>
  <li><a href="#week-11---12-pre-lab-activity-and-week-12-lab-task" id="toc-week-11---12-pre-lab-activity-and-week-12-lab-task" class="nav-link" data-scroll-target="#week-11---12-pre-lab-activity-and-week-12-lab-task">Week 11 - 12 Pre-Lab Activity and Week 12 Lab Task</a>
  <ul class="collapse">
  <li><a href="#submit-scripts" id="toc-submit-scripts" class="nav-link" data-scroll-target="#submit-scripts">Submit Scripts</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../PSYC234/index.html">PSYC234</a></li><li class="breadcrumb-item"><a href="../PSYC234/Week2.html">2. Multiple Regression Including Categorical Predictors</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">2. Multiple Regression Including Categorical Predictors</h1>
<p class="subtitle lead">Emma Mills</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="lecture" class="level1">
<h1>Lecture</h1>
<p><a href="https://lancaster.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=9326aee0-b700-4373-b019-b26401385879&amp;start=0">Lecture Link</a></p>
<section id="materials" class="level2">
<h2 class="anchored" data-anchor-id="materials">Materials</h2>
<p>There are two folders to download for week 12: I separated the materials into files tha R will upload, or should upload with no error; and .docx or .pdf files that R would not like. Please store the second folder somewhere for your use.</p>
<ul>
<li>The first folder is a zipped folder called Week 12 234 Materials.zip. It can be downloaded <a href="data/Wk2/Week_12_234_Materials.zip">here</a>. You can upload the zip file directly on to the R server and it will populate a new folder with the files and data files automatically.</li>
<li>The second folder is called “Week_12_234_Slides_Codebook”. The slides are for the lecture; the Codebook is paired with the “student-por.csv” dataset, for the pre-lab and lab activity is available in a folder for download <a href="data/Wk2/Week_12_234_Slides_Codebook">here</a>.</li>
</ul>
</section>
<section id="pre-lab-activity" class="level2">
<h2 class="anchored" data-anchor-id="pre-lab-activity">Pre-Lab Activity</h2>
<ol type="1">
<li>Watch the lecture before you attempt anything!</li>
<li>Download the zip files and upload to your R account</li>
<li>In the <code>Week 12 Lab Materials</code> folder is an <code>Outputs</code> folder - go and find the <code>Model Summary Output.png</code> file and have a look at the regression model output</li>
<li>Begin by interpreting the model summary, as far as you can (as we did in Lab 11).</li>
<li>Next get the analysis work flow diagram and begin to think about what piece of code do you need for each stage</li>
<li>Start a script and import the dataset. Use the lecture and the model script <code>Multiple_Regression_Categorical_Predictors_2025.Rmd</code> in the <code>Week 12 lecture materials</code> folder to think about what processes may you need to perform to get to a model that looks like the output.</li>
<li>Write a plan of how you might approach an analysis to get to this model</li>
</ol>
<ul>
<li>you could write bullet points against the stages of the analysis workflow diagram</li>
</ul>
<ol start="8" type="1">
<li>You might want to stop at this point - wanting some confirmation from your peers or staff; you could:</li>
</ol>
<ul>
<li><p>post to the discussion forum at this point and we could discuss it</p></li>
<li><p>talk amongst your peers and work together on it in independent study time - forming a small study group for this process</p></li>
<li><p>wait until the lab and bring ideas then…</p>
<p>The first two suggestions will help you grow in confidence faster. I promise, talking to each other - those horizontal conversations - will both let you share understanding, and also identify where some of my messaging is unclear and needs clarification or that the group of you just don’t get it and staff input would be helpful. And at this point, the benefit is that you don’t feel so alone in your uncertainty because you can see that other people are a bit stuck too.</p></li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
My predictor labels and suffixes
</div>
</div>
<div class="callout-body-container callout-body">
<p>The model output has several predictors with suffixes, demarcated by and underscore ’_’ and a letter e.g.&nbsp;’_h’; I explain these in the R Studio demonstrations in the lecture and you can use these as a guide to which kind of processes you may choose to use to transform any variables.</p>
</div>
</div>
</section>
<section id="test-yourself" class="level2">
<h2 class="anchored" data-anchor-id="test-yourself">Test Yourself</h2>
<p>The link to this week’s multiple choice quiz, WBA 2, is <a href="https://modules.lancaster.ac.uk/mod/quiz/view.php?id=2506929">here</a></p>
</section>
<section id="week-12-multiple-regression-with-categorical-predictors" class="level2">
<h2 class="anchored" data-anchor-id="week-12-multiple-regression-with-categorical-predictors">Week 12: Multiple Regression with Categorical Predictors</h2>
<p>In the demonstration sections, you can follow along using the <code>Multiple_Regression_Categorical_Predictors_2025.Rmd</code> file.</p>
<p>We will consider:</p>
<ul>
<li>dummy / treatment contrast coding</li>
<li>changing the reference level</li>
<li>sum coding - preparing for interactions</li>
<li>centring and standardising</li>
<li>Helmert contrast coding for ordinal variables</li>
</ul>
<p>Make sure to load in the following libraries to follow along</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effects)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(PerformanceAnalytics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Keep the model for multiple regression in mind:</p>
<p>You have seen the two predictor regression model equation before; today we have six</p>
<p><span class="math display">\[
Y_i = b_0 + b_1 * X_1 + b_2*X_2 + b_3*X_3 + b_4*X_4 + b_5*X_5 + b_6*X_6 + e_i
\]</span> - The predictors can be a mix of categorical and continuous predictors; there is no different notation between continuous and categorical predictors.</p>
<section id="import-the-data" class="level3">
<h3 class="anchored" data-anchor-id="import-the-data">Import the Data</h3>
<p>The data set is retrieved from https://www.kaggle.com/mirichoi0218/insurance</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/Wk2/Week_12_234_Materials/_Week_12_lecture_materials/insurance.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Looking at the information on reading the data in, we have three variables that R has detected as character variables: sex, smoker and region. Brilliant - three categorical variables.</p>
<p>Just as in any methods section, lets describe our measures:</p>
<ul>
<li><code>sex</code>: a categorical measure of biological sex with two levels: female; male</li>
<li><code>smoker</code>: a categorical measure of smoker status with two levels: no; yes</li>
<li><code>region</code>: a categorical measure of regions for where observations are located with four levels: NE; NW; SE; SW.</li>
<li><code>age</code>: a continuous variable of age in years</li>
<li><code>bmi</code>: a continuous variable of body mass index in BMI units</li>
<li><code>children</code>: a variable (continuous? ordinal?) that describes the number of children within a family, with six levels: 0 - 5</li>
<li><code>charges</code>: the outcome variable; a continous variable that describes expected insurance charges in dollars.</li>
</ul>
<p>If we call a summary on the dataset we will see the variables slightly differently.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age            sex                 bmi           children    
 Min.   :18.00   Length:1338        Min.   :15.96   Min.   :0.000  
 1st Qu.:27.00   Class :character   1st Qu.:26.30   1st Qu.:0.000  
 Median :39.00   Mode  :character   Median :30.40   Median :1.000  
 Mean   :39.21                      Mean   :30.66   Mean   :1.095  
 3rd Qu.:51.00                      3rd Qu.:34.69   3rd Qu.:2.000  
 Max.   :64.00                      Max.   :53.13   Max.   :5.000  
    smoker             region             charges     
 Length:1338        Length:1338        Min.   : 1122  
 Class :character   Class :character   1st Qu.: 4740  
 Mode  :character   Mode  :character   Median : 9382  
                                       Mean   :13270  
                                       3rd Qu.:16640  
                                       Max.   :63770  </code></pre>
</div>
</div>
<p>Here is the first indication that we need a transformation; if we do not explicitly transform the character variables to factor variables, R will do it silently inside the modelling. But we want to be able to see a better level of information about our dataset, so we need to transform them now:</p>
<p>But first, lets tidy up the region level labels by relabelling them. Each level has long label names which will not look good on plots.</p>
</section>
<section id="tidy" class="level3">
<h3 class="anchored" data-anchor-id="tidy">Tidy</h3>
<p>Purely for cosmetic reasons, I am going to change the region variable to acronyms of the geographic regions. This is for labelling of plots:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use nested ifelse() statements</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>region <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(d<span class="sc">$</span>region <span class="sc">==</span> <span class="st">"northeast"</span>, <span class="st">"NE"</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">ifelse</span>(d<span class="sc">$</span>region <span class="sc">==</span> <span class="st">"northwest"</span>, <span class="st">"NW"</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">ifelse</span>(d<span class="sc">$</span>region <span class="sc">==</span> <span class="st">"southeast"</span>, <span class="st">"SE"</span>, <span class="st">"SW"</span>))) </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># change three character variables into factors</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> </span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">factor</span>(sex),</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">smoker =</span> <span class="fu">factor</span>(smoker),</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">region =</span> <span class="fu">factor</span>(region))</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age            sex           bmi           children     smoker    
 Min.   :18.00   female:662   Min.   :15.96   Min.   :0.000   no :1064  
 1st Qu.:27.00   male  :676   1st Qu.:26.30   1st Qu.:0.000   yes: 274  
 Median :39.00                Median :30.40   Median :1.000             
 Mean   :39.21                Mean   :30.66   Mean   :1.095             
 3rd Qu.:51.00                3rd Qu.:34.69   3rd Qu.:2.000             
 Max.   :64.00                Max.   :53.13   Max.   :5.000             
 region      charges     
 NE:324   Min.   : 1122  
 NW:325   1st Qu.: 4740  
 SE:364   Median : 9382  
 SW:325   Mean   :13270  
          3rd Qu.:16640  
          Max.   :63770  </code></pre>
</div>
</div>
<p>Now we can see the number of observations that we have for each level in each categorical variable. We can also see which of the levels in each categorical variable is the reference level. It is the level that is listed first when you call the summary function, so here it is females, non-smokers and the NE region of USA.</p>
</section>
<section id="visualise" class="level3">
<h3 class="anchored" data-anchor-id="visualise">Visualise</h3>
<p>Lets visualise the structure of the variables of the data set:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bar charts for categorical variables</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>p_sex <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(sex), <span class="at">fill =</span> <span class="fu">factor</span>(sex))) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>p_smok <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(smoker), <span class="at">fill =</span> <span class="fu">factor</span>(smoker))) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>p_reg <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(region), <span class="at">fill =</span> <span class="fu">factor</span>(region))) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co"># (so called) continuous variables</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>p_age <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"slateblue"</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>p_age_hist <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="co"># possibly a little more detail using a histogram?</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>p_bmi <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(bmi)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"red"</span>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>p_child <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(children)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p_sex, p_smok, p_reg, p_age_hist, p_bmi, p_child)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week2_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can also look at the relationships between each of the continuous variables: <code>age</code>, <code>bmi</code> and <code>children</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chart.Correlation</span>(d[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">4</span>)], <span class="at">histogram=</span><span class="cn">TRUE</span>, <span class="at">pch=</span><span class="dv">19</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="understand" class="level2">
<h2 class="anchored" data-anchor-id="understand">Understand:</h2>
<section id="model" class="level3">
<h3 class="anchored" data-anchor-id="model">Model</h3>
<p>Our main focus for this week is working with the categorical variables. In regression, group differences are called contrasts and there are several ways to construct contrasts. On import, R will code categorical variables using its default dummy contrast coding scheme.</p>
<p>Take a look and see how R sees the categorical variables; the levels associated with 0 are the reference levels at the moment:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(d<span class="sc">$</span>sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       male
female    0
male      1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(d<span class="sc">$</span>smoker)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    yes
no    0
yes   1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(d<span class="sc">$</span>region)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   NW SE SW
NE  0  0  0
NW  1  0  0
SE  0  1  0
SW  0  0  1</code></pre>
</div>
</div>
<p>During the estimation of the regression model, the reference levels are estimated within the intercept term. This means that you won’t see the labels of the reference levels in any model summary; they are contained within the intercept. To begin with, we will create a model using the raw data, building a model with all six predictor variables. This is the model that you worked with in labs in week 11.</p>
<p>Here is the written regression model:</p>
<p><span class="math display">\[
Charges = b_0 + b_1 * X_{age} + b_2*X_{bmi} + b_3*X_{children} + b_4*X_{sex}+ b_5*X_{smoker} + b_6*X_{region} + e
\]</span></p>
<p>And here is the statistical model for the regression of insurance charges on the 6 predictors, for the raw data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> age <span class="sc">+</span> bmi <span class="sc">+</span> children <span class="sc">+</span> sex <span class="sc">+</span> smoker <span class="sc">+</span> region, d))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age + bmi + children + sex + smoker + 
    region, data = d)

Residuals:
     Min       1Q   Median       3Q      Max 
-11304.9  -2848.1   -982.1   1393.9  29992.8 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -11938.5      987.8 -12.086  &lt; 2e-16 ***
age            256.9       11.9  21.587  &lt; 2e-16 ***
bmi            339.2       28.6  11.860  &lt; 2e-16 ***
children       475.5      137.8   3.451 0.000577 ***
sexmale       -131.3      332.9  -0.394 0.693348    
smokeryes    23848.5      413.1  57.723  &lt; 2e-16 ***
regionNW      -353.0      476.3  -0.741 0.458769    
regionSE     -1035.0      478.7  -2.162 0.030782 *  
regionSW      -960.0      477.9  -2.009 0.044765 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6062 on 1329 degrees of freedom
Multiple R-squared:  0.7509,    Adjusted R-squared:  0.7494 
F-statistic: 500.8 on 8 and 1329 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Remembering that the intercept describes: a female, non-smoker of no age or weight, and no children, who lives in NE USA.</p>
<p>Lets have a quick look at the output and the coefficient labels column. All of the categorical variables are toward the bottom of the list because we entered them toward the end of the list in the model.</p>
<p>Notice how: - the label for <code>sex</code> is <code>sexmale</code>, which tells us that the reference level for the sex variable is female is in the intercept - makes sense since the default is for the first group in the alphabet to be taken as the reference level group. - <code>smoker</code> becomes <code>smokeryes</code> to reflect that being a non-smoker is the reference level group. - the NE region does not have a coefficient in the model summary; since it is the reference level for the region variable, it is contained within the intercept.</p>
</section>
<section id="transform-types-of-categorical-contrasts" class="level3">
<h3 class="anchored" data-anchor-id="transform-types-of-categorical-contrasts">Transform: Types of Categorical Contrasts</h3>
</section>
<section id="dummy-or-treatment-coding-scheme" class="level3">
<h3 class="anchored" data-anchor-id="dummy-or-treatment-coding-scheme">Dummy or Treatment Coding Scheme</h3>
<p>It may make more sense to change the reference level of a variable. Your hypothesis may suggest a particular reference level. You can control the reference level in the dummy coding command: Using the <code>relevel</code>()` function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>smoker <span class="ot">&lt;-</span> <span class="fu">relevel</span>(d<span class="sc">$</span>smoker, <span class="at">ref =</span> <span class="st">"yes"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="fu">relevel</span>(d<span class="sc">$</span>sex, <span class="at">ref =</span> <span class="st">"male"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>region <span class="ot">&lt;-</span> <span class="fu">relevel</span>(d<span class="sc">$</span>region, <span class="at">ref =</span> <span class="st">"SE"</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(d<span class="sc">$</span>sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       female
male        0
female      1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(d<span class="sc">$</span>smoker)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    no
yes  0
no   1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(d<span class="sc">$</span>region)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   NE NW SW
SE  0  0  0
NE  1  0  0
NW  0  1  0
SW  0  0  1</code></pre>
</div>
</div>
<p>Look at the top row for each variable where the zeroes are. Notice how for sex and smoker, the reference levels are now the last word in the alphabet. We have changed the reference levels.</p>
<p>Any model that we now call has a different interpretation on the intercept. The intercept now represents a male, smoker of no age, weight or children that lives in SE USA.</p>
<p>Lets recall the model: No changes to the code here:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> age <span class="sc">+</span> bmi <span class="sc">+</span> children <span class="sc">+</span> sex <span class="sc">+</span> smoker <span class="sc">+</span> region, d))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age + bmi + children + sex + smoker + 
    region, data = d)

Residuals:
     Min       1Q   Median       3Q      Max 
-11304.9  -2848.1   -982.1   1393.9  29992.8 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  10743.66    1116.22   9.625  &lt; 2e-16 ***
age            256.86      11.90  21.587  &lt; 2e-16 ***
bmi            339.19      28.60  11.860  &lt; 2e-16 ***
children       475.50     137.80   3.451 0.000577 ***
sexfemale      131.31     332.95   0.394 0.693348    
smokerno    -23848.53     413.15 -57.723  &lt; 2e-16 ***
regionNE      1035.02     478.69   2.162 0.030782 *  
regionNW       682.06     478.96   1.424 0.154669    
regionSW        74.97     470.64   0.159 0.873460    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6062 on 1329 degrees of freedom
Multiple R-squared:  0.7509,    Adjusted R-squared:  0.7494 
F-statistic: 500.8 on 8 and 1329 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The formula is the same, the residuals are the same, the significance and variance explained is the same. The change is in how the model estimates the coefficients given the reference levels of the variables.</p>
<p>There is no change here for coefficients for our continuous variables. The coefficients for our categorical variables have changed however:</p>
<ul>
<li><code>sexfemale</code> now describes the difference in charges when you move from being male to female. The magnitude of the coefficient remains the same however the direction of the effect is reversed. Before changing the reference level, the coefficient was negative, now it is positive. Changing from male to female is associated with an increase in insurance charges of approximately $131.00.</li>
<li><code>smokerno</code> now describes the difference in charges when you move from being smoker to a non-smoker. The magnitude of the coefficient remains the same however the direction of the effect is reversed. Before changing the reference level, the coefficient was positive, now it is negative. Changing from being a smoker to a non-smoker is associated with a decrease in insurance charges of approximately $23,848.00.</li>
<li>changing the <code>region</code> reference level from NE to SE now describes the difference in charges between residents of SE USA and the other regions. First look at the NE coefficient - that has stayed the same value but has changed direction. This is because NE used to be the reference level and this coefficient was always describing a difference in charges between NE and SE USA. Living in the NE is associated with higher insurance charges. The other two coefficients have changed in both direction and magnitude. We can infer from this that the SE region is associated with the lower insurance charges across the group of regions because all the coefficients are postive, indicating an increase in insurance charges relative to the SE. The coefficients have changed in magnitude because they now describe a different relationship - between SE and themselves rather than NE.</li>
</ul>
<p>The big change here is in the intercept. By changing the reference levels, the intercept is now positive - people are amassing insurance charges, which makes more sense. I am guessing that it is the huge coefficient of the <code>smoker</code> variable that has effected this change.</p>
<p>We will keep the reference levels like this going forward.</p>
</section>
<section id="a-quick-check-of-model-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="a-quick-check-of-model-diagnostics">A Quick Check of Model Diagnostics</h3>
<p>Has our model explained all the structured variance? Lets look at diagnostic plots before we go any further:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)) <span class="co"># display plots in a 2 x 2 panel</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week2_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>So, we know little about these variables, and we haven’t even looked at the individual coefficients in the summary outputs. We know that the model for the six predictors is significant but we can see that the percentage of variance explained in the <code>charges</code> variable is 75%. Looking at the residuals plot above, there is still a lot of clustering in the residuals, however. And clustering should indicate to you that the residuals have some correlated relationship between them. Which means we are either missing some predictors that would explain this correlation or the linear model is not a good choice of model. Quite often, you would begin to consider interaction terms when you see this level of correlation in the residuals - we will consider interactions in week 13.</p>
<p>If you are going to put interactions into a regression model, and you want to mix categorical and continuous predictors in the interaction term, there is a more effective contrast scheme to use with your categorical variables: Sum or Deviation Contrasts.</p>
</section>
<section id="sum-or-deviation-coding-schemes" class="level3">
<h3 class="anchored" data-anchor-id="sum-or-deviation-coding-schemes">Sum or Deviation Coding Schemes</h3>
<p>So, lets think about interactions - introduced in the context of ANOVA last term and thinking about many of the presentations in the 204 module at the end of last term, they are germain to the structure of experimental design whenever groups are included.</p>
<p>What interactions could be plausible here? Just using what we know about medical problems and charges and the variables we have - could there be an interaction between <code>bmi</code> and <code>smoker</code> status? Or <code>bmi</code> and <code>gender</code> for females who are experiencing the menopause? Do lifestyle choices cluster together to effect medical insurance charges? Does the number of children covered by insurance vary systematically by region?</p>
<p>Plausible interactions from the perspective of a layman (me) and I am not going to model them here. But it may inform the choice of contrasting scheme. If we want to interpret interactions between variables later on - either a mix of continuous and categorical or both categorical predictors, it makes sense to use sum coding. And even though we have one categorical variable with four levels (region), we can still do this.</p>
<p>It’s a good idea to make copies of variables so that your original variables remain intact. I am making new variables with the suffix ‘sum’ so I know these are the sum coded ones</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># copy categorical variables to the same dataset with a suffix to denote sum coding status</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sexsum =</span> sex,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">smokersum =</span> smoker,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">regionsum =</span> region) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(d<span class="sc">$</span>sexsum) <span class="co"># dummy coded right now</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       female
male        0
female      1</code></pre>
</div>
</div>
<p>Now do the transformation using the <code>contr.sum()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">contrasts</span>(d<span class="sc">$</span>sexsum) <span class="ot">&lt;-</span> <span class="fu">contr.sum</span>(<span class="dv">2</span>)) <span class="co"># levels are now 1 and -1 and variable is now centred at 0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [,1]
1    1
2   -1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># repeat for the other two variables</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>(<span class="fu">contrasts</span>(d<span class="sc">$</span>smokersum) <span class="ot">&lt;-</span> <span class="fu">contr.sum</span>(<span class="dv">2</span>)) <span class="co"># levels are now 1 and -1 and variable is now centred at 0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [,1]
1    1
2   -1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">contrasts</span>(d<span class="sc">$</span>regionsum) <span class="ot">&lt;-</span> <span class="fu">contr.sum</span>(<span class="dv">4</span>)) <span class="co"># levels are now 1 and -1 but variable is not centred (because this isn't a binary variable)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [,1] [,2] [,3]
1    1    0    0
2    0    1    0
3    0    0    1
4   -1   -1   -1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(d<span class="sc">$</span>regionsum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   [,1] [,2] [,3]
SE    1    0    0
NE    0    1    0
NW    0    0    1
SW   -1   -1   -1</code></pre>
</div>
</div>
<p>Critically, it is the levels of the variable that are at ‘1’ that will be reported in the model summary. So here: males, smokers and SE, NE and NW of region. Lets refit the regression model using this contrast scheme:</p>
<p>I am calling my model <code>m6_sum</code> to remind me that the model still has six predictors but the categorical variables are now sum coded.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m6_sum <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> age <span class="sc">+</span> bmi <span class="sc">+</span> children <span class="sc">+</span> sexsum <span class="sc">+</span> smokersum <span class="sc">+</span> regionsum, d))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age + bmi + children + sexsum + smokersum + 
    regionsum, data = d)

Residuals:
     Min       1Q   Median       3Q      Max 
-11304.9  -2848.1   -982.1   1393.9  29992.8 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -666.94     968.64  -0.689 0.491239    
age           256.86      11.90  21.587  &lt; 2e-16 ***
bmi           339.19      28.60  11.860  &lt; 2e-16 ***
children      475.50     137.80   3.451 0.000577 ***
sexsum1       -65.66     166.47  -0.394 0.693348    
smokersum1  11924.27     206.58  57.723  &lt; 2e-16 ***
regionsum1   -448.01     291.24  -1.538 0.124219    
regionsum2    587.01     293.11   2.003 0.045411 *  
regionsum3    234.05     292.92   0.799 0.424427    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6062 on 1329 degrees of freedom
Multiple R-squared:  0.7509,    Adjusted R-squared:  0.7494 
F-statistic: 500.8 on 8 and 1329 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The intercept has changed once more. It is now negative once more. We still see no material changes in the significance of the model or the effects, however. Telling us that while we are changing the way we are modelling our variables, we are not changing the relationships within the data.</p>
<ul>
<li>see how the binary categorical variables of <code>sex</code> and <code>smoker</code> coefficients are half what they were when dummy coded. You can see that the estimates are halved from the <code>m6</code> model that uses dummy / treatment contrast coding.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># raw coefficient for sex divided by 2</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co"># see the raw data model that we ran first</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">131.3</span> <span class="sc">/</span> <span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -65.65</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># raw coefficient for smoker divided by 2</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fl">23848.5</span> <span class="sc">/</span> <span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11924.25</code></pre>
</div>
</div>
<p>In order to find the insurance charges for the -1 levels, we have to use the equation. Lets do some math to demonstrate this:</p>
<p>Sex: The <code>sex</code> variable is our fourth predictor, so our maths equation looks like this:</p>
<p><span class="math display">\[
Y_i = b_0 + b_4 * X_{sex}
\]</span></p>
<p>We need:</p>
<ul>
<li>the <code>intercept</code> term = <span class="math inline">\(b_0\)</span> = (-666.94)</li>
<li>the coefficient value for <code>sexsum1</code> (-65.66) from the model output; this is the fourth predictor, so if we had written out our equation for all the predictors, it would be <span class="math inline">\(b_4\)</span> (as above)</li>
<li>we also need the labels for the two levels of the sex predictor: male (1) and female (-1) because we are going to put those in our <span class="math inline">\(X_4\)</span> part of the equation.</li>
</ul>
<p>Here we go:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># charges for being male</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>(InsuranceCharge_Male <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">666.94</span> <span class="sc">+</span> (<span class="sc">-</span><span class="fl">65.66</span> <span class="sc">*</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -732.6</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># charges for being female</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>(InsuranceCharge_Female <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">666.94</span> <span class="sc">+</span> (<span class="sc">-</span><span class="fl">65.66</span> <span class="sc">*</span> <span class="sc">-</span><span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -601.28</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the difference between being male or female</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">732.6</span> <span class="sc">-</span> <span class="sc">-</span><span class="fl">601.28</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -131.32</code></pre>
</div>
</div>
<p>The difference in insurance charges between females and males is still showing to be around $130.00 - which is the same value as in the dummy coded model</p>
<p>Lets do the math for the <code>smoker</code> variable:</p>
<p>The <code>smoker</code> variable is our fifth predictor, so our maths equation looks like this:</p>
<p><span class="math display">\[
Y_i = b_0 + b_5 * X_{smoker}
\]</span></p>
<p>We need:</p>
<ul>
<li>the <code>intercept</code> term = <span class="math inline">\(b_0\)</span> = (-666.94)</li>
<li>the coefficient value for <code>smokersum1</code> (11924.27) from the model output; this is the fifth predictor, so if we had written out our equation for all the predictors, it would be <span class="math inline">\(b_5\)</span> (as above)</li>
<li>we also need the labels for the two levels of the smoker variable: yes (1) and no (-1) because we are going to put those in our <span class="math inline">\(X_5\)</span> part of the equation.</li>
</ul>
<p>Here we go:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>(InsuranceCharge_smoker <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">666.94</span> <span class="sc">+</span> (<span class="fl">11924.27</span> <span class="sc">*</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11257.33</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>(InsuranceCharge_nonsmoker <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">666.94</span> <span class="sc">+</span> (<span class="fl">11924.27</span> <span class="sc">*</span> <span class="sc">-</span><span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -12591.21</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fl">11257.33</span><span class="sc">-</span> <span class="sc">-</span><span class="fl">12591.21</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 23848.54</code></pre>
</div>
</div>
<p>The difference in insurance charges between non-smokers and smokers is still showing the same value as in the dummy coded model</p>
<p>The <code>region</code> variable has four levels, NE, NW, SE and SW. It is sum-coded in our model at the moment. Because it has four levels it is a little harder to interpret than the categorical variables with two levels. Lets take a look at how R sees the variable levels in sum-coding format again; I don’t know about you but I cannot hold the levels in my head for a long time and continually call them to remind myself when working this way.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(d<span class="sc">$</span>regionsum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   [,1] [,2] [,3]
SE    1    0    0
NE    0    1    0
NW    0    0    1
SW   -1   -1   -1</code></pre>
</div>
</div>
<p>SE, NE and NW each have a value of 1 with the other values on their respective rows showing as zero, which represents the intercept. So the coefficients that are shown in the model summary are telling us the difference in insurance charges from the intercept, for those regions. SE is region1 and so on…</p>
<p>If we want to find the predicted value of insurance charges for a person who lives in the southwest, we have to do some more maths. Lets get the summary of the model here again to reduce the need to scroll up:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m6_sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age + bmi + children + sexsum + smokersum + 
    regionsum, data = d)

Residuals:
     Min       1Q   Median       3Q      Max 
-11304.9  -2848.1   -982.1   1393.9  29992.8 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -666.94     968.64  -0.689 0.491239    
age           256.86      11.90  21.587  &lt; 2e-16 ***
bmi           339.19      28.60  11.860  &lt; 2e-16 ***
children      475.50     137.80   3.451 0.000577 ***
sexsum1       -65.66     166.47  -0.394 0.693348    
smokersum1  11924.27     206.58  57.723  &lt; 2e-16 ***
regionsum1   -448.01     291.24  -1.538 0.124219    
regionsum2    587.01     293.11   2.003 0.045411 *  
regionsum3    234.05     292.92   0.799 0.424427    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6062 on 1329 degrees of freedom
Multiple R-squared:  0.7509,    Adjusted R-squared:  0.7494 
F-statistic: 500.8 on 8 and 1329 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We need:</p>
<ul>
<li>the <code>intercept</code> term = <span class="math inline">\(b_0\)</span> = (-666.94)</li>
<li>the three coefficient values for SE = <code>regionsum1</code> (-448.01), NE = <code>regionsum2</code> (587.01) and NW = <code>regionsum3</code> (234.05) from the model output; The signs on the coefficients are critical for an accurate calculation so ensure that you have them right.</li>
</ul>
<p>We can either:</p>
<ul>
<li>add region SE, NE and NW together to find the value for the SW region or</li>
<li>to find the insurance charges for a person who lives in the SW region, we add SE, NE and NW to the intercept value.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add SE, NE and NW values together to get the insurance cost of living in the SW</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="co"># add those to the intercept</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="co"># don't forget the minus signs on the coefficients</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">666.94</span> <span class="sc">+</span> (<span class="sc">-</span><span class="fl">448.01</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">587.01</span> <span class="sc">+</span> <span class="fl">234.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1467.91</code></pre>
</div>
</div>
<p>The insurance charges for living in SW USA = $1467.91. So, it looks as if the model is predicting lower insurance costs for a person who lives in the southwest region</p>
<p>If you want to find out the difference between say, living in SW USA and NW USA, then you have to take SE and NE away from SW</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># difference in insurance charges for a person who lives in SE and SW USA</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">800.97</span> <span class="sc">-</span> (<span class="sc">-</span><span class="fl">448.01</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">587.01</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 234.05</code></pre>
</div>
</div>
<p>If you want to find out the difference between a person living in SW and SE, then you have to take away NE and NW</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">800.97</span> <span class="sc">-</span> (<span class="fl">234.05</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">587.01</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -448.01</code></pre>
</div>
</div>
<p>If we go back to the contrast matrix once more:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(d<span class="sc">$</span>regionsum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   [,1] [,2] [,3]
SE    1    0    0
NE    0    1    0
NW    0    0    1
SW   -1   -1   -1</code></pre>
</div>
</div>
<p>And look down each column, then the quicker way to find out these differences between pairs of regions is to multiply each value by -1. So the difference between living in SW and SE is $448.01</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">448.01</span><span class="sc">*-</span><span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 448.01</code></pre>
</div>
</div>
</section>
<section id="unbalanced-binary-variables" class="level3">
<h3 class="anchored" data-anchor-id="unbalanced-binary-variables">Unbalanced Binary Variables</h3>
<p>When binary variables are unbalanced, you can transform them into numerical variables nd mean-centre them.</p>
<p>Look back at the visualisations of the dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bar charts for categorical variables</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>p_sex <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> sexsum, <span class="at">fill =</span> sexsum)) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>p_smok <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> smokersum, <span class="at">fill =</span> smokersum)) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>p_reg <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> regionsum, <span class="at">fill =</span> regionsum)) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a><span class="co"># (so called) continuous variables</span></span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>p_age <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"slateblue"</span>)</span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>p_age_hist <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="co"># possibly a little more detail using a histogram?</span></span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a>p_bmi <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(bmi)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"red"</span>)</span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a>p_child <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(children)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span>
<span id="cb69-11"><a href="#cb69-11" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p_sex, p_smok, p_reg, p_age_hist, p_bmi, p_child)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week2_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Female and male participants in the <code>sex</code> variable are quite evenly spread. <code>smoker</code> status, however, is very unbalanced.</p>
<p>For categorical variables of two levels (binary variables), Gelman (2007) recommends creating a new numeric variable and then mean centring the new numeric version of the variable. If you use this method, do this across each binary categorical variable for consistency.</p>
<p>Here are the actual numbers for the <code>smoker</code> variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">factor</span>(d<span class="sc">$</span>smoker))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 yes   no 
 274 1064 </code></pre>
</div>
</div>
<p>To create a new numeric variable: I give the new variable a suffix of _n, this tells me it is a numeric version of the original variable and keeps the raw form of the original variable intact.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>smoker_n <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(d<span class="sc">$</span>smoker <span class="sc">==</span> <span class="st">"yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Have a look at what the summary of the new variable shows;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d<span class="sc">$</span>smoker_n) <span class="co"># unbalanced variable - look at the mean value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.0000  0.0000  0.2048  0.0000  1.0000 </code></pre>
</div>
</div>
<p>If this variable had equal numbers of smokers and non-smokers then the mean would be about 0.5 - half way between 1. However, there are many more zeros for non-smokers and this pulls the mean of the variable towards zero.</p>
<section id="mean-centring-a-variable" class="level4">
<h4 class="anchored" data-anchor-id="mean-centring-a-variable">Mean Centring a Variable</h4>
<p>A mean centred variable is made by subtracting the mean of the variable from each observation in the variable.</p>
<ul>
<li>So all the non-smokers who are 0, will have 0.2048 subtracted from them, and will show as -0.2048.</li>
<li>And all the smokers who are 1, will have 0.2048 subtracted from them and so will show as approximately 0.7952</li>
</ul>
<p>I have created a further variable with ’_c’, to show it is mean-centred</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>smoker_c <span class="ot">&lt;-</span> <span class="fu">round</span>(d<span class="sc">$</span>smoker_n <span class="sc">-</span> <span class="fu">mean</span>(d<span class="sc">$</span>smoker_n), <span class="dv">3</span>) <span class="co"># round to 3 figures for readability</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Taking a look at the summary of the variable should show you the minimum (non-smokers) and maximum (smokers) values in the variable</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d<span class="sc">$</span>smoker_c) <span class="co">#</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
-0.2050000 -0.2050000 -0.2050000 -0.0002167 -0.2050000  0.7950000 </code></pre>
</div>
</div>
<p>have a look at the first 5 rows of the centred smoker variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(d<span class="sc">$</span>smoker_c, <span class="dv">5</span>) <span class="co"># smoker was 1 so is the positive numbers; </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  0.795 -0.205 -0.205 -0.205 -0.205</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>                    <span class="co"># non-smoker was zero so is the negative numbers here.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>So here we have observations for yes, no, no, no, no.</p>
<p>Let’s refit the model with the new centred <code>smoker_c</code> variable. I have changed the model name to <code>m6_cen</code> to show that I am now using centred variables as well:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m6_cen <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> age <span class="sc">+</span> bmi <span class="sc">+</span> children <span class="sc">+</span> sexsum <span class="sc">+</span> smoker_c <span class="sc">+</span> regionsum, d))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age + bmi + children + sexsum + smoker_c + 
    regionsum, data = d)

Residuals:
     Min       1Q   Median       3Q      Max 
-11304.9  -2848.1   -982.1   1393.9  29992.8 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -7702.26     963.56  -7.994 2.82e-15 ***
age           256.86      11.90  21.587  &lt; 2e-16 ***
bmi           339.19      28.60  11.860  &lt; 2e-16 ***
children      475.50     137.80   3.451 0.000577 ***
sexsum1       -65.66     166.47  -0.394 0.693348    
smoker_c    23848.53     413.15  57.723  &lt; 2e-16 ***
regionsum1   -448.01     291.24  -1.538 0.124219    
regionsum2    587.01     293.11   2.003 0.045411 *  
regionsum3    234.05     292.92   0.799 0.424427    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6062 on 1329 degrees of freedom
Multiple R-squared:  0.7509,    Adjusted R-squared:  0.7494 
F-statistic: 500.8 on 8 and 1329 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The smoker_c now describes the full value of predictions that the model makes for insurance charges, rather than half of the value under the sum contrast coding scheme. And the intercept has changed again! It is even more negative than before - this is probably because, with the centred smoker variable, the model intercept is now representing non-smokers, and we know that they pay a lot les than smokers for their insurance. There is no change in our model output; remember the change we made was to help us for when we want to use interactions.</p>
</section>
</section>
<section id="mean-centering-continuous-variables" class="level3">
<h3 class="anchored" data-anchor-id="mean-centering-continuous-variables">Mean Centering Continuous Variables</h3>
<p>However, once you begin to centre variables, it is a good idea to do it for all variables - including the continuous ones. While you are learning, it’s a good idea to do it longhand:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create new variables to keep the original variables intact:</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a><span class="co"># transforming the binary variable of sex to be inline with the other variables.</span></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>sex_n <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(d<span class="sc">$</span>sex <span class="sc">==</span> <span class="st">"female"</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> </span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex_c =</span> sex_n <span class="sc">-</span> <span class="fu">mean</span>(sex_n),</span>
<span id="cb83-8"><a href="#cb83-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">age_c =</span> age <span class="sc">-</span> <span class="fu">mean</span>(age), <span class="co"># new variable = old variable minus the mean of the old variable</span></span>
<span id="cb83-9"><a href="#cb83-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">bmi_c =</span> bmi <span class="sc">-</span> <span class="fu">mean</span>(bmi),</span>
<span id="cb83-10"><a href="#cb83-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">child_c =</span> children <span class="sc">-</span> <span class="fu">mean</span>(children))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You do not lose any information by doing these transformation. You can check this by visualising the variables once more.<br>
Redraw the plots and check the x axis values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bar charts for categorical variables</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>p_sex <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> sex_c, <span class="at">fill =</span> sex_c)) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>p_smok <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> smoker_c, <span class="at">fill =</span> smoker_c)) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>p_reg <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> regionsum, <span class="at">fill =</span> regionsum)) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a><span class="co"># (so called) continuous variables</span></span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a>p_age <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> age_c)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"slateblue"</span>)</span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a>p_age_hist <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> age_c)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="co"># possibly a little more detail using a histogram?</span></span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a>p_bmi <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(bmi_c)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"red"</span>)</span>
<span id="cb84-10"><a href="#cb84-10" aria-hidden="true" tabindex="-1"></a>p_child <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(child_c)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span>
<span id="cb84-11"><a href="#cb84-11" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p_sex, p_smok, p_reg, p_age_hist, p_bmi, p_child)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week2_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Note now that the axes are centred around zero for the now centred continuous predictors. The mid-point of the distributions of observations are also hovering around the zero mark. Note also how no information has changed within and between the variables - all relative relationships remain the same.</li>
</ul>
<p>Lets plug the centred continuous variables and the <code>sex_c</code> centred variable into the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m6_cen_all <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> age_c <span class="sc">+</span> bmi_c <span class="sc">+</span> child_c <span class="sc">+</span> sex_c <span class="sc">+</span> smoker_c <span class="sc">+</span> regionsum, d))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age_c + bmi_c + child_c + sex_c + smoker_c + 
    regionsum, data = d)

Residuals:
     Min       1Q   Median       3Q      Max 
-11304.9  -2848.1   -982.1   1393.9  29992.8 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  13289.1      165.9  80.079  &lt; 2e-16 ***
age_c          256.9       11.9  21.587  &lt; 2e-16 ***
bmi_c          339.2       28.6  11.860  &lt; 2e-16 ***
child_c        475.5      137.8   3.451 0.000577 ***
sex_c         -131.3      332.9  -0.394 0.693348    
smoker_c     23848.5      413.1  57.723  &lt; 2e-16 ***
regionsum1    -448.0      291.2  -1.538 0.124219    
regionsum2     587.0      293.1   2.003 0.045411 *  
regionsum3     234.1      292.9   0.799 0.424427    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6062 on 1329 degrees of freedom
Multiple R-squared:  0.7509,    Adjusted R-squared:  0.7494 
F-statistic: 500.8 on 8 and 1329 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Remember that by centring our continuous predictors, the intercepts now represents the continuous predictors at the sample average.</p>
<p>So what does the intercept represent now? A non-smoking female of approximately 40 year of age, with a BMI value of about 30 units, with one child, who lives in SW USA. That makes more sense.</p>
<p>You’ll notice that there is a change on the intercept value. The intercept is no longer a negative unit value. Although it would be nice to think that people could pay negative insurance charges - what does that mean? That everyone is in debt? That the health treatment costs less than 0?</p>
<p>And the centred variable of <code>sex_c</code> now describes the full value of moving from female (in the intercept) to male for changes in insurance charges.</p>
</section>
<section id="standardising-variables" class="level3">
<h3 class="anchored" data-anchor-id="standardising-variables">Standardising Variables</h3>
<p>Create some more variables to store the standardised variables, which we will create next.</p>
<p>Remember to create a standardised variable, we first centre the variable and then divide it by its standard deviation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create new variables to store the standardised values</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="co"># I use _z1 because they are z-scores that are made by dividing by 1 standard deviation</span></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a><span class="co"># these are standardised by dividing by 1 x sd:</span></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> </span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age_z1 =</span> (age <span class="sc">-</span> <span class="fu">mean</span>(age)) <span class="sc">/</span> <span class="fu">sd</span>(age), <span class="co"># new variable = centred variable divided by the standard deviation of the centred variable</span></span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">bmi_z1 =</span> (bmi <span class="sc">-</span> <span class="fu">mean</span>(bmi)) <span class="sc">/</span> <span class="fu">sd</span>(bmi),</span>
<span id="cb87-8"><a href="#cb87-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">child_z1 =</span> (children <span class="sc">-</span> <span class="fu">mean</span>(children)) <span class="sc">/</span> <span class="fu">sd</span>(children),</span>
<span id="cb87-9"><a href="#cb87-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">sex_z1 =</span> sex_c <span class="sc">/</span> <span class="fu">sd</span>(sex_c),</span>
<span id="cb87-10"><a href="#cb87-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">smoker_z1 =</span> smoker_c <span class="sc">/</span> <span class="fu">sd</span>(smoker_c)</span>
<span id="cb87-11"><a href="#cb87-11" aria-hidden="true" tabindex="-1"></a>         )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bar charts for categorical variables</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>p_sex_c <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> sex_z1, <span class="at">fill =</span> sex_z1)) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>p_smok_c <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> smoker_z1, <span class="at">fill =</span> smoker_z1)) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>p_regsum <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> regionsum, <span class="at">fill =</span> regionsum)) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a><span class="co"># frequency polygons for (so called) continuous variables</span></span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>p_age_z1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> age_z1)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="co"># possibly a little more detail using a histogram?</span></span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a>p_bmi_z1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(bmi_z1)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"red"</span>)</span>
<span id="cb88-9"><a href="#cb88-9" aria-hidden="true" tabindex="-1"></a>p_child_z1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(child_z1)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span>
<span id="cb88-10"><a href="#cb88-10" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p_sex_c, p_smok_c, p_regsum, p_age_z1, p_bmi_z1, p_child_z1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week2_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Only the axes have changed once more….the centre is still zero but the units are now in standard deviations.</p>
<p>This line of code charts correlations between columns 18 - 20 of the dataset <code>d</code> - i.e.&nbsp;the standardised varaibles we just made. The correlation coefficients are exactly the same as those that are between the raw variables (see earlier in the script).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chart.Correlation</span>(d[, <span class="fu">c</span>(<span class="dv">18</span><span class="sc">:</span><span class="dv">20</span>)], <span class="at">histogram=</span><span class="cn">TRUE</span>, <span class="at">pch=</span><span class="dv">19</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week2_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="refit-the-model-with-standardised-variables" class="level4">
<h4 class="anchored" data-anchor-id="refit-the-model-with-standardised-variables">Refit the Model with Standardised Variables</h4>
<p>What happens when we use the standardised variables with the centred binary variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m6_z <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> age_z1 <span class="sc">+</span> bmi_z1 <span class="sc">+</span> child_z1 <span class="sc">+</span> sex_z1 <span class="sc">+</span> smoker_z1 <span class="sc">+</span> regionsum, d))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age_z1 + bmi_z1 + child_z1 + sex_z1 + 
    smoker_z1 + regionsum, data = d)

Residuals:
     Min       1Q   Median       3Q      Max 
-11304.9  -2848.1   -982.1   1393.9  29992.8 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 13289.09     165.95  80.079  &lt; 2e-16 ***
age_z1       3608.82     167.18  21.587  &lt; 2e-16 ***
bmi_z1       2068.47     174.40  11.860  &lt; 2e-16 ***
child_z1      573.21     166.12   3.451 0.000577 ***
sex_z1        -65.68     166.53  -0.394 0.693348    
smoker_z1    9627.51     166.79  57.723  &lt; 2e-16 ***
regionsum1   -448.01     291.24  -1.538 0.124219    
regionsum2    587.01     293.11   2.003 0.045411 *  
regionsum3    234.05     292.92   0.799 0.424427    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6062 on 1329 degrees of freedom
Multiple R-squared:  0.7509,    Adjusted R-squared:  0.7494 
F-statistic: 500.8 on 8 and 1329 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The intercept is the same, because no reference levels have changed; <code>sex</code> and <code>smoker</code> are now smaller; the direction of effects remains similar: males are associated with less insurance charges, and smokers are associated with more than non-smokers. The region coefficients are the same because we didn’t change them; The magnitude of the coefficients for age, bmi and children are now bigger. But look at their t values - they have not changed. Nor is the variance explained.</p>
<p>The gift of standardisation is that is calms down the model - gone is the huge $23,848 prediction for smokers. And now we can see the relative strengths of predictors. Smoking is the strongest predictor, followed by age and weight, with each associated with a positive relationship on insurance charges - as they increase so does insurance.</p>
</section>
<section id="transform-standardising-by-two-standard-deviations---extra" class="level4">
<h4 class="anchored" data-anchor-id="transform-standardising-by-two-standard-deviations---extra">Transform: Standardising by Two Standard Deviations - extra</h4>
<p>This is useful to know if you want to have your continuous variables act as if they are a dichotomous variable - so age = young or old / high or low. This is not on the class test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create new variables to store the standardised values</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="co"># these are standardised by dividing by 1 x sd:</span></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> </span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age_z2 =</span> (age <span class="sc">-</span> <span class="fu">mean</span>(age)) <span class="sc">/</span> (<span class="dv">2</span><span class="sc">*</span><span class="fu">sd</span>(age)), <span class="co"># new variable = centred variable divided by the standard deviation of the centred variable</span></span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">bmi_z2 =</span> (bmi <span class="sc">-</span> <span class="fu">mean</span>(bmi)) <span class="sc">/</span> (<span class="dv">2</span><span class="sc">*</span><span class="fu">sd</span>(bmi)),</span>
<span id="cb92-7"><a href="#cb92-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">child_z2 =</span> (children <span class="sc">-</span> <span class="fu">mean</span>(children)) <span class="sc">/</span> (<span class="dv">2</span><span class="sc">*</span><span class="fu">sd</span>(children))</span>
<span id="cb92-8"><a href="#cb92-8" aria-hidden="true" tabindex="-1"></a>         )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bar charts for categorical variables</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>p_sex_c <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> sex_c, <span class="at">fill =</span> sex_c)) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>p_smok_c <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> smoker_c)) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>p_regsum <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> regionsum, <span class="at">fill =</span> regionsum)) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a><span class="co"># frequency polygons for (so called) continuous variables</span></span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a>p_age_z2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> age_z2)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="co"># possibly a little more detail using a histogram?</span></span>
<span id="cb93-8"><a href="#cb93-8" aria-hidden="true" tabindex="-1"></a>p_bmi_z2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(bmi_z2)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"red"</span>)</span>
<span id="cb93-9"><a href="#cb93-9" aria-hidden="true" tabindex="-1"></a>p_child_z2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(child_z2)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span>
<span id="cb93-10"><a href="#cb93-10" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p_sex_c, p_smok_c, p_regsum, p_age_z2, p_bmi_z2, p_child_z2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week2_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Only the axes have changed once more….the centre is still zero, the units are still in standard deviations and look how the range is from a minus to the centre and then a centre to the plus. Two jumps to move from one end of the values to other end - a little bit like the sum coding procedure of moving from -1 to 1 in two jumps.</p>
<p>As I said, you may not use this very much, but it might be a handy little trick in your future - you never know!</p>
</section>
</section>
<section id="ordered-variables" class="level3">
<h3 class="anchored" data-anchor-id="ordered-variables">Ordered Variables?</h3>
<p>Consider the <code>children</code> variable - so far I have treated it as a continuous variable but it’s categorical: look at the histogram above again. There are no values between the distinct categories.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d<span class="sc">$</span>children) <span class="co"># summary as a continuous predictor</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.000   0.000   1.000   1.095   2.000   5.000 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d<span class="sc">$</span>children_f <span class="ot">&lt;-</span> <span class="fu">factor</span>(d<span class="sc">$</span>children)) <span class="co"># wrap the factorising command within a summary command for speed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  0   1   2   3   4   5 
574 324 240 157  25  18 </code></pre>
</div>
</div>
<p>The variable <code>children</code> could also be considered as ordinal in that within a family, birth order has meaning. This gives us an opportunity to look at a final level of contrast coding for ordinal variables - <code>helmert</code> contrast coding.</p>
<p><code>Helmert</code> contrasts can work forwards and backwards. The default function that we are going to use in R works backwards. This means that each coefficient represents the difference in Y for the level in the factor, compared to all the previous levels (or the mean of the previous levels) in the factor.</p>
<p>Lets look at an example to make this a little bit more clear:</p>
<p>First we transform our <code>children</code> variable into a <code>helmert</code> contrasted variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a new variable first</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>children_h <span class="ot">&lt;-</span> <span class="fu">factor</span>(d<span class="sc">$</span>children)</span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a><span class="co"># and then apply an ordered contrast scheme</span></span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a>(<span class="fu">contrasts</span>(d<span class="sc">$</span>children_h) <span class="ot">&lt;-</span> <span class="fu">contr.helmert</span>(<span class="dv">6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [,1] [,2] [,3] [,4] [,5]
1   -1   -1   -1   -1   -1
2    1   -1   -1   -1   -1
3    0    2   -1   -1   -1
4    0    0    3   -1   -1
5    0    0    0    4   -1
6    0    0    0    0    5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co"># levels(d$children_h) # checking the order of levels in the children_h variable</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You don’t have to fully understand this matrix. This level of detail will not be on the class test. However, some of you will appreciate the detail.</p>
<p>Look at column [ ,1] first. This tells us that the first beta coefficient for this variable in the model output will be the comparison between the first two categories of the <code>children_h</code> variable, which is between families with no children and families with one child.</p>
<p>Now look at column [ ,2]. This tells us that the second beta coefficient for the variable will show a comparison between families with two children and families with either no children or one child and so on.</p>
<p>Lets fit the model one last time and include this helmert contrasted variable</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m6_zh <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> age_z1 <span class="sc">+</span> bmi_z1 <span class="sc">+</span> children_h <span class="sc">+</span> sex_z1 <span class="sc">+</span> smoker_z1 <span class="sc">+</span> regionsum, d))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age_z1 + bmi_z1 + children_h + sex_z1 + 
    smoker_z1 + regionsum, data = d)

Residuals:
     Min       1Q   Median       3Q      Max 
-11689.4  -2902.6   -943.7   1492.2  30042.7 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 13893.32     337.07  41.218  &lt; 2e-16 ***
age_z1       3613.56     167.40  21.587  &lt; 2e-16 ***
bmi_z1       2054.53     174.48  11.775  &lt; 2e-16 ***
children_h1   195.49     210.68   0.928  0.35362    
children_h2   480.10     148.35   3.236  0.00124 ** 
children_h3    72.19     130.47   0.553  0.58017    
children_h4   439.92     245.53   1.792  0.07341 .  
children_h5   -11.94     243.80  -0.049  0.96094    
sex_z1        -64.10     166.47  -0.385  0.70025    
smoker_z1    9622.62     167.19  57.557  &lt; 2e-16 ***
regionsum1   -441.62     291.54  -1.515  0.13006    
regionsum2    591.52     293.16   2.018  0.04382 *  
regionsum3    211.47     293.68   0.720  0.47160    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6059 on 1325 degrees of freedom
Multiple R-squared:  0.7519,    Adjusted R-squared:  0.7497 
F-statistic: 334.7 on 12 and 1325 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The <code>children_h</code> predictor has an separate coefficient for each level of the categorical variable. Previously, we had entered the <code>children</code> predictor as continuous, and we were getting an even rate of change in charges for each increase in one child to a family, which registered as a significant impact on insurance charges.</p>
<p>First of all, check the residuals and the significance of the model; the maximum residual value is slightly bigger on this model. And the F ratio is smaller. This indicates to me that there is now more information in the residuals - which tells me that this is not as good a fit for the data as the last model. The variance explained has not changed, so we have estimated more coefficients, and generated more error for no real increase in explanatory power.</p>
<p>However, we want to understand a little bit about helmert contrasts so we will carry on.</p>
<p>Now that we have transformed the variable, our interpretation of the model needs to change somewhat. The rate of change in insurance charges across the increase in children is not even (480.10 is not the same as 72.19). This is not a linear relationship (are we violating some of the model assumptions here?).</p>
<p>Look at <code>children_h1</code>, the difference in insurance charges between families with no children and families with one child is approximately $195.00.</p>
<p>Look at <code>children_h2</code>: the difference in insurance charges for families with two children and both families with one child <em>and</em> families with no children is approximately $480.00…and so on…</p>
<p>The only significantly different change in insurance charges is the change from 0 or 1 child to two child families. Can you think of a reason why a familiy of two children is predicted to pay significantly higher insurance charges than a family of one child?</p>
<p>For the purposes of model checking and reporting, we do not use this model; we revert back to the standardised model.</p>
</section>
<section id="checking-model-assumptions-and-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="checking-model-assumptions-and-diagnostics">Checking Model Assumptions and Diagnostics</h3>
<p>Every regression model is built upon the following assumptions:</p>
<ol type="1">
<li>The relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is assumed to be linear (additive)</li>
<li>The residual errors are normally distributed</li>
<li>The residuals have constant variance (homoscedasticity)</li>
<li>The residuals are not correlated (assumption of independence)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)) <span class="co"># display plots in a 2 x 2 panel</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m6_z) <span class="co"># plot diagnostic plots for m6_zh</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week2_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Residuals vs Fitted</strong>: “fitted” here means the predicted values. We want the pink line to align pretty closely with the horizontal dashed line. Comparing this plot with that from the simple regression, this plot looks better.</p>
<p><strong>Normal Q-Q</strong>: If the residual points (open circles) follow the dashed line, you can assume the residuals are normally distributed. It doesn’t look great on the right hand side, does it?</p>
<p><strong>Scale-Location</strong>: This is checking for constant variance in the residuals - not much here. A good indication would be a horizontal pink line with equally spread points. Our graph is not good.</p>
<p><strong>Residuals vs Leverage</strong> - are there any points that are having a large influence on the regression results. They will be numbered and you can then inspect them in your data file. Observations that show standardised residuals (see the table above) above 3 would be problematic. As would observations of a hat value above <span class="math inline">\(2(p+1)/n\)</span> where <span class="math inline">\(p\)</span> = is the number of predictors (but see below) and <span class="math inline">\(n\)</span> = is the number of observations</p>
<section id="a-different-way-to-observe-points-with-high-leverage-and-high-influence" class="level4">
<h4 class="anchored" data-anchor-id="a-different-way-to-observe-points-with-high-leverage-and-high-influence">A different way to observe points with high leverage and high influence:</h4>
<p>In last week’s script, with a small data set, we used a formula for calculating hat values and Cook’s Distance values and looked across some values after calling our residuals using the <code>augment</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">head</span>(m6z_metrics <span class="ot">&lt;-</span> <span class="fu">augment</span>(m6_z)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 13
  charges age_z1 bmi_z1 child_z1 sex_z1 smoker_z1 regionsum .fitted  .resid
    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt; &lt;fct&gt;       &lt;dbl&gt;   &lt;dbl&gt;
1  16885. -1.44  -0.453  -0.908  -1.01      1.97  SW         25294. -8409. 
2   1726. -1.51   0.509  -0.0787  0.989    -0.508 SE          3449. -1723. 
3   4449. -0.798  0.383   1.58    0.989    -0.508 SE          6707. -2258. 
4  21984. -0.442 -1.31   -0.908   0.989    -0.508 NW          3755. 18230. 
5   3867. -0.513 -0.292  -0.908   0.989    -0.508 NW          5592. -1726. 
6   3757. -0.584 -0.807  -0.908  -1.01     -0.508 SE          3720.    36.8
# ℹ 4 more variables: .hat &lt;dbl&gt;, .sigma &lt;dbl&gt;, .cooksd &lt;dbl&gt;, .std.resid &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Columns 1 - 7 are our variables. <code>fitted</code> and <code>residuals</code> are the predicted values of charges and the <code>error</code> values, respectively. And last week we manually inspected the <code>.hat</code> and the <code>.cooksd</code> column for values that were above a certain threshold.</p>
<p>But this dataset has over 1000 observations. Plus, we are modelling both continuous and categorical predictors. It gets hard to manually inspect dataframes that have many observations and even harder to manage this for complex models. So an easier way is to have R sort out your high influence and leverage values and then plot them:</p>
</section>
<section id="graphing-model-hat-values-and-observations-with-high-leverage" class="level4">
<h4 class="anchored" data-anchor-id="graphing-model-hat-values-and-observations-with-high-leverage">Graphing Model Hat Values and Observations with High Leverage:</h4>
<ol type="1">
<li>calculate hat value using the formula</li>
<li>use the hat value and filter out any observations from the augmented dataset that are above the threshold</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">coefficients</span>(m6_z)) <span class="co"># number of parameters estimated by the model</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">nrow</span>(d) <span class="co"># number of observations</span></span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-4"><a href="#cb106-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-5"><a href="#cb106-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 1) calulate the hat value</span></span>
<span id="cb106-6"><a href="#cb106-6" aria-hidden="true" tabindex="-1"></a>(m6z_hat <span class="ot">&lt;-</span> (<span class="dv">2</span><span class="sc">*</span>(p<span class="sc">+</span><span class="dv">1</span>))<span class="sc">/</span>N)  <span class="co"># model hat value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01494768</code></pre>
</div>
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2) filter out observations that are above the hat value in the augmented dataset</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>m6z_hatvalues <span class="ot">&lt;-</span> m6z_metrics <span class="sc">%&gt;%</span> </span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.hat <span class="sc">&gt;</span> <span class="fl">0.01494768</span>) </span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-5"><a href="#cb108-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2) this is equivalent code, rather than hard coding the hat value, you put in the </span></span>
<span id="cb108-6"><a href="#cb108-6" aria-hidden="true" tabindex="-1"></a><span class="co"># object label that we just created for the hat value on line 663</span></span>
<span id="cb108-7"><a href="#cb108-7" aria-hidden="true" tabindex="-1"></a>m6z_hatvalues_1 <span class="ot">&lt;-</span> m6z_metrics <span class="sc">%&gt;%</span> </span>
<span id="cb108-8"><a href="#cb108-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.hat <span class="sc">&gt;</span> m6z_hat) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Four residuals are showing values of larger than the model hat value.</p>
<ol start="3" type="1">
<li>Plot them: <code>hat.plot</code> function taken from Kabacoff, (2022), R in Action.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>hat.plot <span class="ot">&lt;-</span> <span class="cf">function</span>(fit) {</span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a>              p <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">coefficients</span>(fit))</span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a>              n <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">fitted</span>(fit))</span>
<span id="cb109-4"><a href="#cb109-4" aria-hidden="true" tabindex="-1"></a>              <span class="fu">plot</span>(<span class="fu">hatvalues</span>(fit), <span class="at">main=</span><span class="st">"Index Plot of Hat Values"</span>)</span>
<span id="cb109-5"><a href="#cb109-5" aria-hidden="true" tabindex="-1"></a>              <span class="fu">abline</span>(<span class="at">h=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>)<span class="sc">*</span>p<span class="sc">/</span>n, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb109-6"><a href="#cb109-6" aria-hidden="true" tabindex="-1"></a>              <span class="fu">identify</span>(<span class="dv">1</span><span class="sc">:</span>n, <span class="fu">hatvalues</span>(fit), <span class="fu">names</span>(<span class="fu">hatvalues</span>(fit)))</span>
<span id="cb109-7"><a href="#cb109-7" aria-hidden="true" tabindex="-1"></a>            }</span>
<span id="cb109-8"><a href="#cb109-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-9"><a href="#cb109-9" aria-hidden="true" tabindex="-1"></a><span class="fu">hat.plot</span>(m6_z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week2_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
</div>
<p>Checking for observations that are influential follows a similar pattern: observations that exceed the <em>Cook’s distance</em> value = <span class="math inline">\(4/(n-p-1)\)</span> are likely to have high influence and the regression results may change if you exclude them. In the presence of such observations that exceed Cook’s distance, unless you know the observation are errors, you probably need to estimate the model without the observations and report both sets of results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>(m6z_Cooks <span class="ot">&lt;-</span> <span class="dv">4</span><span class="sc">/</span>(N<span class="sc">-</span>p<span class="dv">-1</span>)) <span class="co"># model Cook's distance value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.003012048</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a>m6z_Cooksvalues <span class="ot">&lt;-</span> m6z_metrics <span class="sc">%&gt;%</span> </span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.cooksd <span class="sc">&gt;</span> <span class="fl">0.003012048</span>) </span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-4"><a href="#cb113-4" aria-hidden="true" tabindex="-1"></a><span class="co"># or</span></span>
<span id="cb113-5"><a href="#cb113-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-6"><a href="#cb113-6" aria-hidden="true" tabindex="-1"></a>m6z_Cooksvalues_1 <span class="ot">&lt;-</span> m6z_metrics <span class="sc">%&gt;%</span> </span>
<span id="cb113-7"><a href="#cb113-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.cooksd <span class="sc">&gt;</span> m6z_Cooks) </span>
<span id="cb113-8"><a href="#cb113-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-9"><a href="#cb113-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 83 residuals</span></span>
<span id="cb113-10"><a href="#cb113-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-11"><a href="#cb113-11" aria-hidden="true" tabindex="-1"></a><span class="co"># make sure your dataset is in nrow() function</span></span>
<span id="cb113-12"><a href="#cb113-12" aria-hidden="true" tabindex="-1"></a><span class="co"># and your model is before $coefficients and in the plot line</span></span>
<span id="cb113-13"><a href="#cb113-13" aria-hidden="true" tabindex="-1"></a><span class="co"># here it is m6_z</span></span>
<span id="cb113-14"><a href="#cb113-14" aria-hidden="true" tabindex="-1"></a><span class="co"># when you are ready to draw the plot</span></span>
<span id="cb113-15"><a href="#cb113-15" aria-hidden="true" tabindex="-1"></a><span class="co"># select all three lines at once and press control and enter</span></span>
<span id="cb113-16"><a href="#cb113-16" aria-hidden="true" tabindex="-1"></a><span class="co"># or rerun the chunk by pressing the green arrow in the top right hand corner.</span></span>
<span id="cb113-17"><a href="#cb113-17" aria-hidden="true" tabindex="-1"></a>cutoff <span class="ot">&lt;-</span> <span class="dv">4</span><span class="sc">/</span>(<span class="fu">nrow</span>(d)<span class="sc">-</span><span class="fu">length</span>(m6_z<span class="sc">$</span>coefficients)<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb113-18"><a href="#cb113-18" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m6_z, <span class="at">which=</span><span class="dv">4</span>, <span class="at">cook.levels=</span>cutoff)</span>
<span id="cb113-19"><a href="#cb113-19" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span>cutoff, <span class="at">lty=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week2_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There are 83 observations that appear to be influential within the dataset, however the three labelled here are particularly offensive. If we were to continue our analysis at this point, we may be be filtering out some observations and running the model once more as a sensitivity analysis.</p>
</section>
</section>
</section>
<section id="communicate" class="level2">
<h2 class="anchored" data-anchor-id="communicate">Communicate:</h2>
<p>Lets reprint the summary to save scrolling but also save the summary to an object so that we can call the values while interpreting and reporting the model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>(m6_z_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(m6_z))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age_z1 + bmi_z1 + child_z1 + sex_z1 + 
    smoker_z1 + regionsum, data = d)

Residuals:
     Min       1Q   Median       3Q      Max 
-11304.9  -2848.1   -982.1   1393.9  29992.8 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 13289.09     165.95  80.079  &lt; 2e-16 ***
age_z1       3608.82     167.18  21.587  &lt; 2e-16 ***
bmi_z1       2068.47     174.40  11.860  &lt; 2e-16 ***
child_z1      573.21     166.12   3.451 0.000577 ***
sex_z1        -65.68     166.53  -0.394 0.693348    
smoker_z1    9627.51     166.79  57.723  &lt; 2e-16 ***
regionsum1   -448.01     291.24  -1.538 0.124219    
regionsum2    587.01     293.11   2.003 0.045411 *  
regionsum3    234.05     292.92   0.799 0.424427    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6062 on 1329 degrees of freedom
Multiple R-squared:  0.7509,    Adjusted R-squared:  0.7494 
F-statistic: 500.8 on 8 and 1329 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>A results section for multiple regression may have three parts</p>
<ul>
<li>Descriptive statistics for continuous variables and quantities of observations in each categorty for categorical variables</li>
<li>A correlation matrix that shows bivariate correlations between the continuous predictors</li>
<li>A model summary and some narrative text to communicate the predictions from the model</li>
</ul>
<section id="descriptive-statistics" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-statistics">Descriptive Statistics</h3>
<p>Depending on your hypothesis, you may report descriptive statistics differently from here. For instance if a hypothesis was present for an interaction of any of the predictors with sex, then the descriptive statistics section would be presented with means and sd and categories for the other variables split by gender.</p>
<p>In this model, there is a flat structure, - i.e.&nbsp;no interactions, so we will go for basic mean and sd values or number of observations per category. The code below pulls out all the relevant information; I leave it to you to manage the formatting for reporting in a results section.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>(Desc_stat <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> </span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a> <span class="co"># group_by(sex) %&gt;% </span></span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="co"># number of obs in each sex category</span></span>
<span id="cb116-4"><a href="#cb116-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">Age =</span> <span class="fu">round</span>(<span class="fu">mean</span>(age),<span class="dv">1</span>),</span>
<span id="cb116-5"><a href="#cb116-5" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">SD Age</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">sd</span>(age),<span class="dv">1</span>),</span>
<span id="cb116-6"><a href="#cb116-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">BMI =</span> <span class="fu">round</span>(<span class="fu">mean</span>(bmi),<span class="dv">1</span>),</span>
<span id="cb116-7"><a href="#cb116-7" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">SD BMI</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">sd</span>(bmi),<span class="dv">1</span>),</span>
<span id="cb116-8"><a href="#cb116-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">Children =</span> <span class="fu">round</span>(<span class="fu">mean</span>(children),<span class="dv">1</span>),</span>
<span id="cb116-9"><a href="#cb116-9" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">SD Children</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">sd</span>(children), <span class="dv">1</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
      n   Age `SD Age`   BMI `SD BMI` Children `SD Children`
  &lt;int&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;         &lt;dbl&gt;
1  1338  39.2       14  30.7      6.1      1.1           1.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(d<span class="sc">$</span>children)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1   2   3   4   5 
574 324 240 157  25  18 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(d<span class="sc">$</span>smoker)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 yes   no 
 274 1064 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(d<span class="sc">$</span>sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  male female 
   676    662 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(d<span class="sc">$</span>region)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 SE  NE  NW  SW 
364 324 325 325 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="co"># It would be up to you to choose how to arrange a table, given the different numbers of levels across the categorical variables.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="correlations-between-truly-continous-predictors" class="level3">
<h3 class="anchored" data-anchor-id="correlations-between-truly-continous-predictors">Correlations between (truly) continous predictors</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>(d_cor <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> </span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(age, bmi, children) <span class="sc">%&gt;%</span> </span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb127-4"><a href="#cb127-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.dist</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb127-5"><a href="#cb127-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          age  bmi
bmi      0.11     
children 0.04 0.01</code></pre>
</div>
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The output here could be a second table</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="inferential-statistics---model-coefficients-ses-t-values-and-p-values" class="level3">
<h3 class="anchored" data-anchor-id="inferential-statistics---model-coefficients-ses-t-values-and-p-values">Inferential Statistics - Model Coefficients, SEs, <em>t</em>-values and <em>p</em> values</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get model predictions / coefficients</span></span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a>Estimate <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">coef</span>(m6_z), <span class="dv">2</span>)</span>
<span id="cb130-3"><a href="#cb130-3" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the coefficient standard errors</span></span>
<span id="cb130-4"><a href="#cb130-4" aria-hidden="true" tabindex="-1"></a>SE <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcov</span>(m6_z)))</span>
<span id="cb130-5"><a href="#cb130-5" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the t-value of the t-test for each predictors coefficient</span></span>
<span id="cb130-6"><a href="#cb130-6" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">round</span>((Estimate <span class="sc">/</span> SE), <span class="dv">2</span>)</span>
<span id="cb130-7"><a href="#cb130-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the p-values of the predictors from the model</span></span>
<span id="cb130-8"><a href="#cb130-8" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">summary</span>(m6_z)<span class="sc">$</span>coefficients[, <span class="st">"Pr(&gt;|t|)"</span>], <span class="dv">3</span>)</span>
<span id="cb130-9"><a href="#cb130-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-10"><a href="#cb130-10" aria-hidden="true" tabindex="-1"></a>Predictor <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Intercept"</span>, <span class="st">"Age"</span>, <span class="st">"BMI"</span>, <span class="st">"No. of Children"</span>,</span>
<span id="cb130-11"><a href="#cb130-11" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Sex: Male"</span>, <span class="st">"Smoker: Yes"</span>,<span class="st">"Region: SE"</span>,</span>
<span id="cb130-12"><a href="#cb130-12" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Region: NE"</span>, <span class="st">"Region: NW"</span>)</span>
<span id="cb130-13"><a href="#cb130-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-14"><a href="#cb130-14" aria-hidden="true" tabindex="-1"></a>Model_values <span class="ot">&lt;-</span> <span class="fu">data_frame</span>(Predictor,Estimate, SE, t, p,)</span>
<span id="cb130-15"><a href="#cb130-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-16"><a href="#cb130-16" aria-hidden="true" tabindex="-1"></a><span class="co"># tidy up p-values</span></span>
<span id="cb130-17"><a href="#cb130-17" aria-hidden="true" tabindex="-1"></a>Model_values<span class="sc">$</span>p <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(p <span class="sc">==</span> <span class="fl">0.000</span>, <span class="st">"&lt; .001"</span>, p)</span>
<span id="cb130-18"><a href="#cb130-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-19"><a href="#cb130-19" aria-hidden="true" tabindex="-1"></a>Model_values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 5
  Predictor       Estimate    SE     t p     
  &lt;chr&gt;              &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; 
1 Intercept        13289.   166. 80.1  &lt; .001
2 Age               3609.   167. 21.6  &lt; .001
3 BMI               2068.   174. 11.9  &lt; .001
4 No. of Children    573.   166.  3.45 0.001 
5 Sex: Male          -65.7  167. -0.39 0.693 
6 Smoker: Yes       9628.   167. 57.7  &lt; .001
7 Region: SE        -448.   291. -1.54 0.124 
8 Region: NE         587.   293.  2    0.045 
9 Region: NW         234.   293.  0.8  0.424 </code></pre>
</div>
</div>
<p>I have given you some code above that shows you how to manually extract the values that we have used in the model outputs to form a table to be able to report the values. The broom package does this also. However, on small models (for numbers of predictors), I like the level of control to be able to do it like this. You may find another way as you learn and that is good too.</p>
<p>I leave it to you to format the <code>Model_values</code> dataframe into a table for presentation. Remember to also report your F ratio for the model and its significance value along with the variance explained.</p>
</section>
<section id="reporting-text" class="level3">
<h3 class="anchored" data-anchor-id="reporting-text">Reporting Text</h3>
<p>We conducted a multiple regression for the association of several predictor variables with the outcome variable of insurance charges. We standardised all continuous predictors as well as the predictors for Sex and Smoker Status. Region is a sum-coded variable, with South West being the reference level variable.</p>
<p>Without engaging in any sensitivity analysis or outlier analysis, we report a model with a full set of predictors. The model is significant (<span class="math inline">\(F(8, 1329)\)</span> = 500.81, <em>p</em> &lt; 0.001). This set of predictors explains 75.09% of the variance in insurance charges.</p>
<p>The following details the significant predictors in this model. Each value represents the change in insurance charges for a one standard deviation change in the predictor, holding all other variables constant.</p>
<p>Age shows a positive association with insurance charges, with an increase in approximately $3608 for a one standard deviation unit change on the age scale (age: <em>t</em> = 21.59, <em>p</em> &lt; .001). A person’s body mass index (BMI) also shows a positive relationship and increases insurance charges by approximately $2068 with a one standard deviation change in BMI score (<em>t</em> = 11.86, <em>p</em> &lt; .001). An increase in number of children in a family was positively associated with an increase in insurance charges (<em>b</em> = 573.21, <em>t</em> = 3.45, <em>p</em> &lt; .001). Being a male individual is negatively associated with insurance charges, lowering insurance costs by approximately $65, however this increase is non-significant (<em>t</em> = -0.39, <em>p</em> = .693). Being a smoker is significantly and positively associated with an increase in insurance charges, raising insurance costs by approximately $9,627 (<em>t</em> = 57.72, <em>p</em> &lt; .001). While living in the northeast region of the country also shows a positive association with insurance charges compared to living in the southwest region (reference level), showing an increase of around $587 (<em>t</em> = 2, <em>p</em> = 0.045).</p>
<p>We should be cautious with these interpretations as the residuals show that there is unexplained variability and there are a number of observations that are indicated as having high leverage or high influence so further terms and sensitivity analyses are warranted for a fuller understanding.</p>
</section>
<section id="plotting-predictions" class="level3">
<h3 class="anchored" data-anchor-id="plotting-predictions">Plotting predictions</h3>
<p>Plotting an individual effect (or lack of it) is very simple if we are not too worried about being pretty. Plus - because we haven’t changed any of the essential information in any of the coding / centring schemes, you can choose how to plot them, based upon the model. This is the skill of the communication part - which plot would make more sense to your reader - a plot with a standardised x-axis or a plot with raw units on the x-axis?</p>
<p>Look at the x-axis on the following two plots to compare and make your considered decision:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="co"># standardised variable plot</span></span>
<span id="cb132-2"><a href="#cb132-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predictorEffect</span>(<span class="st">"age_z1"</span>, m6_z))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week2_files/figure-html/unnamed-chunk-62-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="co"># raw unit plot</span></span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predictorEffect</span>(<span class="st">"age"</span>, m6))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week2_files/figure-html/unnamed-chunk-62-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here are the plots for the predictors from the final model, but you could change the code to reflect the predictor labels and the model labels. Just be consistent - choose one scale rather than jumping between multiple scales for your plots.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predictorEffect</span>(<span class="st">"age_z1"</span>, m6_z))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week2_files/figure-html/unnamed-chunk-63-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predictorEffect</span>(<span class="st">"bmi_z1"</span>, m6_z))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week2_files/figure-html/unnamed-chunk-63-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predictorEffect</span>(<span class="st">"child_z1"</span>, m6_z))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week2_files/figure-html/unnamed-chunk-63-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predictorEffect</span>(<span class="st">"sex_z1"</span>, m6_z))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week2_files/figure-html/unnamed-chunk-63-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predictorEffect</span>(<span class="st">"smoker_z1"</span>, m6_z))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week2_files/figure-html/unnamed-chunk-63-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predictorEffect</span>(<span class="st">"regionsum"</span>, m6_z))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week2_files/figure-html/unnamed-chunk-63-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I think plotting of the effects is probably much better for communication using the effects from the model with the raw data (the first model). I leave it to you to adapt the code to make this change.</p>
<p>But the model building is not complete. It is likely that there are interactions that could be put into the model and age, as a variable, may be nonlinear - how to deal with both of these is for the next lecture.</p>
<p>There are lots of things to do as we run a multiple regression model - both before, while and after building the model, which will be the focus of the future lectures. We need to look at:</p>
<ul>
<li>a model with some significant predictors! - done</li>
<li>correlation matrices - done</li>
<li>centering predictors - done</li>
<li>standardising predictors - done</li>
<li>models with categorical predictors - done &amp; ongoing
<ul>
<li>interpreting models with categorical predictors - done &amp; ongoing</li>
</ul></li>
<li>models with interaction terms</li>
<li>the properties of multicollinearity</li>
<li>choosing between different models</li>
<li>reporting models - ongoing</li>
</ul>
</section>
</section>
<section id="week-11---12-pre-lab-activity-and-week-12-lab-task" class="level2">
<h2 class="anchored" data-anchor-id="week-11---12-pre-lab-activity-and-week-12-lab-task">Week 11 - 12 Pre-Lab Activity and Week 12 Lab Task</h2>
<p>In this lab, you will be working with the R script, data and Codebook stored <a href="Week_12_234_Materials.zip_materials.zip">here</a>, and the accompanying codebook is accessed <a href="data/Wk2/Data_Codebook.pdf">here</a>.</p>
<p>Work through the Week12_R_Script.Rmd file and enter in your own code to arrive at the following model summary and figures. All these images are stored in the Outputs folder that comes down in the Week 12 .zip file:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Images/Wk2/Model Summary Output.png" class="img-fluid figure-img"></p>
<figcaption>Model summary</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Images/Wk2/Visualise_Predictors.png" class="img-fluid figure-img"></p>
<figcaption>Visualise Predictors</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Images/Wk2/Visualise_Bivariate_Correlations.png" class="img-fluid figure-img"></p>
<figcaption>Visualise Correlations</figcaption>
</figure>
</div>
<p><img src="Images/Wk2/Predictor_plot_absences_z1.png" class="img-fluid" alt="Predictor Absence"> <img src="Images/Wk2/Predictor_Plot_health_z1.png" class="img-fluid" alt="Predictor Health"> <img src="Images/Wk2/Predictor_Plot_school_c.png" class="img-fluid" alt="Predictor School"> <img src="Images/Wk2/Predictor_plot_walc_h.png" class="img-fluid" alt="Predictor Walc"> <img src="Images/Wk2/PredictorPlot_sex_c.png" class="img-fluid" alt="Predictor Sex"></p>
<section id="submit-scripts" class="level3">
<h3 class="anchored" data-anchor-id="submit-scripts">Submit Scripts</h3>
<p>Remember to submit your group scripts if you want the chance to receive feedback on your own and other groups’ scripts.</p>


</section>
</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../PSYC234/Week1.html" class="pagination-link" aria-label="1. Review of correlation, simple regression and demonstration of multiple regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">1. Review of correlation, simple regression and demonstration of multiple regression</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../PSYC234/Week3.html" class="pagination-link" aria-label="3. Multiple regression models that include interactions (moderated variables)">
        <span class="nav-page-text">3. Multiple regression models that include interactions (moderated variables)</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Website developed by Matthew Ivory</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../previous-content/index.html">
<p>Previous Content</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>