<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistics for Psychologists - 3. Multiple Regression Models that Include Interactions (Moderated Variables)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../PSYC234/Week4.html" rel="next">
<link href="../PSYC234/Week2.html" rel="prev">
<link href="../Images/favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="../site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="../site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="../site_libs/viz-1.8.2/viz.js"></script>
<link href="../site_libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet">
<script src="../site_libs/grViz-binding-1.0.11/grViz.js"></script>
<script>window.onload = function() {document.getElementById("autocomplete-0-input").placeholder = "Search Year 2";};</script>
<script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="https://lu-psy-r.github.io/essentials/index_24.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="https://lu-psy-r.github.io/">
    <span class="navbar-title">Statistics for Psychologists</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year1/index.html"> 
<span class="menu-text">Year 1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year2/index.html"> 
<span class="menu-text">Year 2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year3/index.html"> 
<span class="menu-text">Year 3</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/MSc/index.html"> 
<span class="menu-text">MSc</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/more/index.html"> 
<span class="menu-text">And More…</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../PSYC234/index.html">PSYC234</a></li><li class="breadcrumb-item"><a href="../PSYC234/Week3.html">3. Multiple Regression Models that Include Interactions (Moderated Variables)</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../PSYC214/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC214</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Measurement, Variance and Inferential Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. One-Factor Between-Participants ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Assumptions of ANOVA and Follow-Up Procedures</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. One-Factor Within-Participants ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Revision of One-Factor ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Introduction to Factorial Designs and Interactions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Two-Factor Between-Participants ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Two-Factor Mixed and Within-Participants ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC214/Week9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Three-Factor ANOVA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../PSYC234/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC234</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Review of correlation, simple regression and demonstration of multiple regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Multiple Regression Including Categorical Predictors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week3.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">3. Multiple Regression Models that Include Interactions (Moderated Variables)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Mediation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Factor Analysis and the Binomial Test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Wilcoxon rank-sum test and Wilcoxon signed-rank test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Kruskal-Wallis test and Friedman’s ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Binary logistic regression models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC234/Week9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Expanding on binary logistic regression</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#lecture" id="toc-lecture" class="nav-link active" data-scroll-target="#lecture">Lecture</a>
  <ul class="collapse">
  <li><a href="#slides" id="toc-slides" class="nav-link" data-scroll-target="#slides">Slides</a></li>
  <li><a href="#materials" id="toc-materials" class="nav-link" data-scroll-target="#materials">Materials</a></li>
  <li><a href="#pre-lab-activity" id="toc-pre-lab-activity" class="nav-link" data-scroll-target="#pre-lab-activity">Pre-Lab Activity</a></li>
  <li><a href="#lab-task" id="toc-lab-task" class="nav-link" data-scroll-target="#lab-task">Lab Task</a></li>
  <li><a href="#test-yourself" id="toc-test-yourself" class="nav-link" data-scroll-target="#test-yourself">Test Yourself</a></li>
  <li><a href="#lecture-demonstration-script-for-interactions" id="toc-lecture-demonstration-script-for-interactions" class="nav-link" data-scroll-target="#lecture-demonstration-script-for-interactions">Lecture &amp; Demonstration Script for Interactions</a>
  <ul class="collapse">
  <li><a href="#import" id="toc-import" class="nav-link" data-scroll-target="#import">Import</a></li>
  <li><a href="#tidy" id="toc-tidy" class="nav-link" data-scroll-target="#tidy">Tidy</a></li>
  <li><a href="#visualise" id="toc-visualise" class="nav-link" data-scroll-target="#visualise">Visualise</a></li>
  <li><a href="#correlations-between-continuous-variables" id="toc-correlations-between-continuous-variables" class="nav-link" data-scroll-target="#correlations-between-continuous-variables">Correlations between continuous variables</a></li>
  <li><a href="#transform" id="toc-transform" class="nav-link" data-scroll-target="#transform">Transform</a></li>
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model">Model</a></li>
  <li><a href="#model-diagnostics" id="toc-model-diagnostics" class="nav-link" data-scroll-target="#model-diagnostics">Model diagnostics</a></li>
  <li><a href="#communicate" id="toc-communicate" class="nav-link" data-scroll-target="#communicate">Communicate</a></li>
  <li><a href="#what-are-interaction-terms" id="toc-what-are-interaction-terms" class="nav-link" data-scroll-target="#what-are-interaction-terms">What are interaction terms?</a></li>
  <li><a href="#when-are-interaction-terms-used" id="toc-when-are-interaction-terms-used" class="nav-link" data-scroll-target="#when-are-interaction-terms-used">When are interaction terms used?</a></li>
  <li><a href="#statistical-power-of-interactions" id="toc-statistical-power-of-interactions" class="nav-link" data-scroll-target="#statistical-power-of-interactions">Statistical Power of Interactions</a></li>
  <li><a href="#preparation-of-data-for-using-interactions" id="toc-preparation-of-data-for-using-interactions" class="nav-link" data-scroll-target="#preparation-of-data-for-using-interactions">Preparation of data for using interactions</a></li>
  <li><a href="#building-a-model-with-interactions" id="toc-building-a-model-with-interactions" class="nav-link" data-scroll-target="#building-a-model-with-interactions">Building a model with interactions</a></li>
  </ul></li>
  <li><a href="#model-script" id="toc-model-script" class="nav-link" data-scroll-target="#model-script">Model script</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../PSYC234/index.html">PSYC234</a></li><li class="breadcrumb-item"><a href="../PSYC234/Week3.html">3. Multiple Regression Models that Include Interactions (Moderated Variables)</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">3. Multiple Regression Models that Include Interactions (Moderated Variables)</h1>
<p class="subtitle lead">Emma Mills</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="lecture" class="level1">
<h1>Lecture</h1>
<p><a href="https://lancaster.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=7718c2a4-2676-4b85-ac17-b26d014265c0">Lecture Link</a></p>
<section id="slides" class="level2">
<h2 class="anchored" data-anchor-id="slides">Slides</h2>
<p><a href="data/Wk3/PSYC234_Week_13_Slides_Student.zip">Slides Link</a></p>
</section>
<section id="materials" class="level2">
<h2 class="anchored" data-anchor-id="materials">Materials</h2>
<p>There are two zipped folders to download for week 13:</p>
<ul>
<li>The first folder is a zipped folder called <code>Lecture_Week_13_Materials.zip</code>. It can be downloaded <a href="data/Wk3/Lecture_Week_13_Materials.zip">here</a>. This has the script and the <code>KidIQ.txt</code> file for the model that was demonstrated in the lecture</li>
<li>The second folder is called <code>Lab_Week_13_Materials.zip</code>. In this folder is the <code>WorldHappinessReportData.csv</code> and a half prepared .Rmd file for the lab in week 13. I did this because it is a really interesting dataset but the tidying and visualisation would take forever….please download it <a href="data/Wk3/Lab_Week_13_Materials.zip">here</a>.</li>
</ul>
</section>
<section id="pre-lab-activity" class="level2">
<h2 class="anchored" data-anchor-id="pre-lab-activity">Pre-Lab Activity</h2>
<ol type="1">
<li>Watch the lecture and play with the lecture script before you attempt anything!</li>
<li>Download the zip files and upload to your R account</li>
<li>Look at the model outout above, begin by interpreting the model summary, as far as you can (as we did in Lab in week 11 &amp; 12).</li>
<li>Next get the analysis work flow diagram and begin to think about what piece of code do you need for each stage</li>
<li>Start a script and import the dataset. Use the lecture and the model script as a guide</li>
<li>Write a plan of how you might approach an analysis to get to this model</li>
</ol>
<ul>
<li>you could write bullet points against the stages of the analysis workflow diagram</li>
</ul>
<ol start="7" type="1">
<li>You might want to stop at this point - wanting some confirmation from your peers or staff; you could:</li>
</ol>
<ul>
<li><p>post to the discussion forum at this point and we could discuss it</p></li>
<li><p>talk amongst your peers and work together on it in independent study time - forming a small study group for this process</p></li>
<li><p>wait until the lab and bring ideas then…</p></li>
</ul>
</section>
<section id="lab-task" class="level2">
<h2 class="anchored" data-anchor-id="lab-task">Lab Task</h2>
<p>We are working with the <code>WorldHappinessReportData.csv</code> from the folder listed above. Upload it to the R server, (preferably before you come to the lab) and complete the <code>Multiple_Regression_Interactions_Student.Rmd</code> file using that data.</p>
<p>The model output you are aiming to match is below</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Images/Wk3/Model Output.png" class="img-fluid figure-img"></p>
<figcaption>Model output</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
My predictor labels and suffixes
</div>
</div>
<div class="callout-body-container callout-body">
<p>The model output has several predictors with suffixes, demarcated by an underscore ‘_’ and a letter e.g.&nbsp;‘_h’; I explain these in the R Studio demonstrations in the lecture and you can use these as a guide to which kind of processes you may choose to use to transform any variables.</p>
</div>
</div>
</section>
<section id="test-yourself" class="level2">
<h2 class="anchored" data-anchor-id="test-yourself">Test Yourself</h2>
<p>The link to this week’s multiple choice quiz, WBA 3, is <a href="https://modules.lancaster.ac.uk/mod/quiz/view.php?id=2738522">here</a></p>
</section>
<section id="lecture-demonstration-script-for-interactions" class="level2">
<h2 class="anchored" data-anchor-id="lecture-demonstration-script-for-interactions">Lecture &amp; Demonstration Script for Interactions</h2>
<p>So far we have considered models with multiple variables - of both categorical and continuous types. One property of all these predictors in these models has been that they are functionally independent of each other.<br>
What does functionally independent of each other mean? This means that, irrespective of any correlated relationship that we may have visualised as we got to know the data, when it came to coding the model, we did not let the variables talk to each other. We only let them talk to the outcome variable.<br>
You have met interactions in PSYC214. The focus of this week’s lecture and lab is to introduce interactions in the context of a multiple regression model.</p>
<p>I am also going to introduce a concept called nested modelling. This is where a researcher builds a series of models and with each step, the model takes the previous model and builds directly onto it. In this way, the previous model is contained, or nested, in the latest model.</p>
<p>This strategy of building a model has immediate benefits because you can test for a significant difference between the two models. For instance, when you are unsure about what predictors may make the best fitting model. Or if you were in an exploratory research framework. It can also have benefits for when you have collected confounding or third variables. Finally, if you are unsure that using an interaction term in your model has resulted in a better fit for the data, having two models, with the first model also existing within the larger second model, gives you the opportunity to test for the utility of that interaction term</p>
<p>In summary, this week we are learning about and applying:</p>
<ul>
<li>interaction terms within a multiple regression model</li>
<li>nested modelling</li>
<li>a principled method for saying that one model is a better fit for the data than another</li>
</ul>
<p>While also thinking about the workflow of a good analysis.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Images/Wk3/Wrangle.png" class="img-fluid figure-img"></p>
<figcaption>Workflow</figcaption>
</figure>
</div>
<p>Thinking and acting systematically will a) help your writing of any results section and b) help with your interpretation of models and ideas to write for your discussion section.</p>
<section id="import" class="level3">
<h3 class="anchored" data-anchor-id="import">Import</h3>
<p>Before beginning, I will introduce the dataset to you:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/Wk3/Lecture_Week_13_Materials/KidIQ.txt"</span>, <span class="at">col_types =</span> <span class="fu">cols</span>(<span class="at">mom_work =</span> <span class="fu">col_skip</span>()))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#d &lt;- read_csv("KidIQ.txt", col_types = cols(mom_work = col_skip()))</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   kid_score         mom_hs           mom_iq          mom_age     
 Min.   : 20.0   Min.   :0.0000   Min.   : 71.04   Min.   :17.00  
 1st Qu.: 74.0   1st Qu.:1.0000   1st Qu.: 88.66   1st Qu.:21.00  
 Median : 90.0   Median :1.0000   Median : 97.92   Median :23.00  
 Mean   : 86.8   Mean   :0.7857   Mean   :100.00   Mean   :22.79  
 3rd Qu.:102.0   3rd Qu.:1.0000   3rd Qu.:110.27   3rd Qu.:25.00  
 Max.   :144.0   Max.   :1.0000   Max.   :138.89   Max.   :29.00  </code></pre>
</div>
</div>
<p>There are 434 observations over four variables. A simple dataset for our demonstration. We have:</p>
<ul>
<li><code>kid_score</code>: a continuous variable of test scores for children at 3 years-of-age; this is the outcome variable for this dataset</li>
<li><code>mom_hs</code>: a categorical variable describing whether the mother of the 3-year-old complete their high school education or not. Two levels: 0 = no; 1 = yes</li>
<li><code>mom_iq</code>: a continuous variable of IQ scores of the mothers in this sample. The mean in this sample is 100 - which reflects the wider population average</li>
<li><code>mom_age</code>: a continuous variable of age in years, captured at the time of testing of the child.</li>
</ul>
</section>
<section id="tidy" class="level3">
<h3 class="anchored" data-anchor-id="tidy">Tidy</h3>
<p>From the summary above, it appears to be a tidy dataset in as much as there are no missing observations. Woohoo!</p>
<p>However, <code>mom_hs</code> is currently viewed by R as a numerical variable, when it is a categorical variable. For clarity, lets transform this now before visualising the dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>mom_hs <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(d<span class="sc">$</span>mom_hs)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   kid_score     mom_hs      mom_iq          mom_age     
 Min.   : 20.0   0: 93   Min.   : 71.04   Min.   :17.00  
 1st Qu.: 74.0   1:341   1st Qu.: 88.66   1st Qu.:21.00  
 Median : 90.0           Median : 97.92   Median :23.00  
 Mean   : 86.8           Mean   :100.00   Mean   :22.79  
 3rd Qu.:102.0           3rd Qu.:110.27   3rd Qu.:25.00  
 Max.   :144.0           Max.   :138.89   Max.   :29.00  </code></pre>
</div>
</div>
<p>With that small change, we can see the <code>mom_hs</code> much more clearly. But still, a picture speaks a thousand words…</p>
</section>
<section id="visualise" class="level3">
<h3 class="anchored" data-anchor-id="visualise">Visualise</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bar charts for categorical variables</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>p_hs <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> mom_hs, <span class="at">fill =</span> mom_hs)) <span class="sc">+</span> <span class="fu">geom_bar</span>() <span class="sc">+</span> <span class="fu">theme_classic</span>()</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># (so called) continuous variables</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>p_score <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> kid_score)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()<span class="sc">+</span> <span class="fu">theme_classic</span>()</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>p_iq <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> mom_iq)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()<span class="sc">+</span> <span class="fu">theme_classic</span>()</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>p_age <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(mom_age)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()<span class="sc">+</span> <span class="fu">theme_classic</span>()</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p_score, p_hs, p_iq, p_age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week3_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I have visualised the outcome variable here aswell, to help us get to know a little more about it. Notice also how I have used histograms rather than a smooth density plot for the continuous variables, because they are measured in whole points; there are no fractions of points in these measures. So we can still see the distributoin of the values, but using a histogram may remind you that the granularity of the measurement is in whole units, with no decimal values (not like something like milliseconds, for instance).</p>
<p>Hopefully, after last week’s lecture you will see that the continuous variables all show a pretty tolerable normal curve. You might say that there is a slight negative skew on the kid score and a slight positive skew on the mom_iq, but nothing too drastic.</p>
<p>But look at the <code>mom_hs</code> variable. It is unbalanced - thankfully. Within the group, I hope we all appreciate the value of a basic education. So, within the sample, the mother’s who completed their high school education are represented more than mothers who did not complete thrie high shcool education, at an approximate ratio of 3:1. Quick check - what kind of transformation is indicated here (based on last week’s learning)?</p>
</section>
<section id="correlations-between-continuous-variables" class="level3">
<h3 class="anchored" data-anchor-id="correlations-between-continuous-variables">Correlations between continuous variables</h3>
<p>Because we have multiple predictors of a continuous variables, we may choose to look at (and put a less garish version of) a correlation matrix to understand correlations between pairs of variables before modelling.</p>
<p>Here, I have left in the outcome variable <code>kid_score</code>. You can leave it in or out. It is just for getting to know the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chart.Correlation</span>(d[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">4</span>)], <span class="at">histogram=</span><span class="cn">TRUE</span>, <span class="at">pch=</span><span class="dv">19</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week3_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Reading the correlation matrix
</div>
</div>
<div class="callout-body-container callout-body">
<p>Starting from the top left: From <code>kid_score</code>, move one square to the right and you get <em>r</em> = .45; then move one square down and you hit <code>mom_iq</code>. <em>r</em> = .45 is the correlation between those two variables</p>
<p>From <code>kid_score</code>, move two squares to the right and you get <em>r</em> = .092; then move two squares down and you hit <code>mom_age</code>. <em>r</em> = .092 is the correlation between those two variables</p>
<p>However many squares you count across, count the same amount of squares down to find the paired variable.</p>
</div>
</div>
<p>I am going to leave the majority of the interpretation of this matrix to you for practice, but note one thing. The predictor <code>mom_age</code> is only weakly correlated with both <code>mom_iq</code> and the outcome variable, <code>kid_score</code>. Any thoughts on the whether it will be a significant predictor in a multiple regression model?</p>
</section>
<section id="transform" class="level3">
<h3 class="anchored" data-anchor-id="transform">Transform</h3>
<p>I have an unbalanced variable, <code>mom_hs</code>, so I want to transform this variable. I choose to <code>centre</code> the variable. And by doing so, I should do it for <code>mom_iq</code> and <code>mom_age</code>, to aid with interpretation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(d<span class="sc">$</span>mom_hs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
 93 341 </code></pre>
</div>
</div>
<p>Completing high school = 1 here.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make mom_hs a numeric variable</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>mom_hs_c <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(d<span class="sc">$</span>mom_hs <span class="sc">==</span> <span class="st">"1"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d<span class="sc">$</span>mom_hs_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  1.0000  1.0000  0.7857  1.0000  1.0000 </code></pre>
</div>
</div>
<p>The mean is quite high because of the greater quantity of 1 values in the variable; so when we mean centre, we will subtract 0.7857 from every observation. Consequently, the group of mothers who did not complete high school will be negative values (0-0.7857), while the mothers who did complete high school will be positive numbers (1-0.7857).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># now complete the rescaling by taking the mean away from every observation</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>mom_hs_c <span class="ot">&lt;-</span> d<span class="sc">$</span>mom_hs_c <span class="sc">-</span> <span class="fu">mean</span>(d<span class="sc">$</span>mom_hs_c)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d<span class="sc">$</span>mom_hs_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-0.7857  0.2143  0.2143  0.0000  0.2143  0.2143 </code></pre>
</div>
</div>
<p>Repeat the centring with the two continuous variables. You don’t need to do the <code>ifelse</code> command in this case, as they are already numeric variables</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>mom_iq_c <span class="ot">&lt;-</span> d<span class="sc">$</span>mom_iq <span class="sc">-</span> <span class="fu">mean</span>(d<span class="sc">$</span>mom_iq)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>mom_age_c <span class="ot">&lt;-</span> d<span class="sc">$</span>mom_age <span class="sc">-</span> <span class="fu">mean</span>(d<span class="sc">$</span>mom_age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What do the predictor variables mean now
</div>
</div>
<div class="callout-body-container callout-body">
<p>Remember under raw data, any regression coefficient is the change in the outcome variable for a one unit / level increase in the predictor variable <em>when all other predictors are at zero</em></p>
<p>Now we have mean centred, the interpretation changes: any regression coefficient now represents a change in the outcome variable for a one unit / level increase in the predictor variable <em>when all other predictors are at their sample average</em></p>
</div>
</div>
<p>Scroll back up to the visualisations for the raw data to look for the average IQ score and Age, from the middle of the plots’ x-axes. It is good to have a real number in your head to make sense of the models.</p>
<p>We are ready to build our first model.</p>
</section>
<section id="model" class="level3">
<h3 class="anchored" data-anchor-id="model">Model</h3>
<p>I said I was going to introduce you to the practice of nested modelling in this lecture. We start this by building the first model: The intercept only model, or an empty model. It is also sometimes called the null model, however the definition of a null model is not fixed. A null model can also be a baseline model from which you measure change, and does not necessarily have to be an empty model. While an empty model will always be an empty model because it has no predictors. An intercept model will always be an intercept only model because it only models the intercept.</p>
<section id="the-empty-intercept-only-model" class="level4">
<h4 class="anchored" data-anchor-id="the-empty-intercept-only-model">The Empty / Intercept Only Model</h4>
<p>We can express an empty or intercept only model like this:</p>
<p><span class="math display">\[
Y = b_0 + e
\]</span></p>
<p>The empty or intercept only model for any dataset expresses its mean value of the outcome variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(d<span class="sc">$</span>kid_score)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 86.79724</code></pre>
</div>
</div>
<p>And here is the model as a regression model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> <span class="dv">1</span>, d))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kid_score ~ 1, data = d)

Residuals:
    Min      1Q  Median      3Q     Max 
-66.797 -12.797   3.203  15.203  57.203 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  86.7972     0.9797   88.59   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 20.41 on 433 degrees of freedom</code></pre>
</div>
</div>
<p>The regression coefficient matches the raw mean value I called above. So at this point, we can say that in the sample, the average score for a 3 year old child is approximately 87 points.</p>
</section>
<section id="a-simple-regression---one-predictor" class="level4">
<h4 class="anchored" data-anchor-id="a-simple-regression---one-predictor">A Simple Regression - one predictor</h4>
<p>Let’s add <code>mom_iq</code>. To demonstrate how model <code>m0</code> is nested inside this larger model, I will write the formula out in words</p>
<p><span class="math display">\[
Model zero: Kid\_score = Intercept + error
\]</span></p>
<p><span class="math display">\[
model one: Kid\_score = Intercept + Mom's IQ + error
\]</span></p>
<p>Hopefully, you can see how the first model is in the second model. The change in the second model is the addition of one variable. I call my model <code>m1_c</code> because it has one predictor and it is a centred model.</p>
<p>Here is the equation for the model - for those of you that like the numbers part:</p>
<p><span class="math display">\[
Y = b_0 + b_1 * X_{mom\_iq} + e
\]</span></p>
<p>Here is the code for this one predictor model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1_c <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> mom_iq_c, d))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kid_score ~ 1 + mom_iq_c, data = d)

Residuals:
    Min      1Q  Median      3Q     Max 
-56.753 -12.074   2.217  11.710  47.691 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 86.79724    0.87680   98.99   &lt;2e-16 ***
mom_iq_c     0.60997    0.05852   10.42   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.27 on 432 degrees of freedom
Multiple R-squared:  0.201, Adjusted R-squared:  0.1991 
F-statistic: 108.6 on 1 and 432 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Where are your eyes looking as you first scan the model output? The bottom line first:</p>
<p>The model is significant (<em>F</em>(1, 432) = 108.6, <em>p</em> &lt;.001) and explains approximately 20% of the variance in children’s test scores.</p>
<p>Next the regression coefficient:</p>
<p>For every one point increase in Mother’s IQ, a child’s test score increases by 0.61 of a point (<em>t</em> = 10.42, <em>p</em> &lt; .001).</p>
</section>
<section id="how-do-we-judge-that-any-model-is-a-better-fit-than-any-other-model" class="level4">
<h4 class="anchored" data-anchor-id="how-do-we-judge-that-any-model-is-a-better-fit-than-any-other-model">How do we judge that any model is a better fit than any other model?</h4>
<p>For models that are based <strong>on the same data</strong>, we can perform a test to see if the change in amount of variance explained from the smaller model to the larger model is significantly different.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m0, m1_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: kid_score ~ 1
Model 2: kid_score ~ 1 + mom_iq_c
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1    433 180386                                  
2    432 144137  1     36249 108.64 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>This is how we do it - we call an <code>anova</code> on the two models. Look at the output</p>
<p>From the top of the output, we have</p>
<ul>
<li>the title of the output</li>
<li>the next two lines repeat the model formulae</li>
<li>Beginning with the fourth line, we are presented with an ANOVA table
<ul>
<li>What is important in these lines is:</li>
<li>the number 1 line is for Model 1 in the table (not your model 1)</li>
<li>the number 2 line is for Model 2 in th table</li>
<li>you want to look at the <em>p</em> value; if the <em>p</em> value is lower than &lt; .05, then the difference in the amount of variance explained on the outcome variable between the two models is larger than zero. And the addition of that new variable (here <code>mom_iq</code>) is warranted.</li>
</ul></li>
</ul>
</section>
<section id="a-multiple-regression-with-two-independent-predictors" class="level4">
<h4 class="anchored" data-anchor-id="a-multiple-regression-with-two-independent-predictors">A Multiple Regression with Two Independent Predictors</h4>
<p>Based upon the model comparison that we conducted, <code>m1_c</code> has greater predictive value than <code>m0</code>, so we will carry <code>m1_c</code> forward and introduce another predictor in <code>m2_c</code>. We could now think of <code>m1_c</code> as a null model, because it is the base model with which we will eventually compare <code>m2_c</code>.</p>
<p>We continue with our nesting principle, incrementally building a model, one predictor at a time so that the smaller mode is always present in the larger model. Importantly, we are running all of these models on the same data so that we can use the model comparison technique.</p>
<p><span class="math display">\[
model one: Kid\_score = Intercept + Mom's IQ + error
\]</span></p>
<p><span class="math display">\[
model two: Kid\_score = Intercept + Mom's IQ + Mom's Age + error
\]</span></p>
<p>These two predictors are independent of each other. We are hoping they will each predict a singificant amount of <em>unique</em> variance on Children’s test scores. We can express a model with two independent predictors like this</p>
<p><span class="math display">\[
Y = b_0 + b_1 * X_{mom\_iq} + b_2*X_{mom\_age} + e
\]</span></p>
<p>And we can draw it like this:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Images/Wk3/Diagram_Ind_Predictors.png" class="img-fluid figure-img"></p>
<figcaption>Diagram of Independent Predictors</figcaption>
</figure>
</div>
<p>And the code for a model could look like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2_c <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> mom_iq_c <span class="sc">+</span> mom_age_c, d))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kid_score ~ 1 + mom_iq_c + mom_age_c, data = d)

Residuals:
    Min      1Q  Median      3Q     Max 
-56.941 -12.493   2.257  11.614  46.711 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 86.79724    0.87638   99.04   &lt;2e-16 ***
mom_iq_c     0.60357    0.05874   10.28   &lt;2e-16 ***
mom_age_c    0.38813    0.32620    1.19    0.235    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.26 on 431 degrees of freedom
Multiple R-squared:  0.2036,    Adjusted R-squared:  0.1999 
F-statistic: 55.08 on 2 and 431 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Because I am building multiple models, before I rush to formally interpret this, I am going to perform my model comparison. This time I am going to compare <code>m1_c</code> with <code>m2_c</code>. We don’t need to worry about comparing the intercept only model because it was shown to be the weaker model in our last model comparison.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1_c, m2_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: kid_score ~ 1 + mom_iq_c
Model 2: kid_score ~ 1 + mom_iq_c + mom_age_c
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1    432 144137                           
2    431 143665  1     471.9 1.4157 0.2348</code></pre>
</div>
</div>
<p>As before, from the top of the table:</p>
<ul>
<li>the first line is the title</li>
<li>the second line is the formula for the base model in this comparison</li>
<li>the third line is the formula for the larger model in this comparison</li>
<li>then we have the table itself - look for the <em>p</em> value:
<ul>
<li>if it is lower than &lt; .05, then the difference in the amount of change in the outcome variable between the two models is significant and the addition of the extra variable is warranted.</li>
</ul></li>
</ul>
<p>This comparison between models <code>m1_c</code> and <code>m2_c</code> shows a <em>p</em> value of 0.235. The difference between the models is non-significant. The addition of <code>mom_age_c</code> to the model does not significantly increase the amount of variance explained and so to include this variable in the next stage of model building is not warranted.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Is your non-significant predictor included in your hypotheses?
</div>
</div>
<div class="callout-body-container callout-body">
<p>If your non-significant predictor is included in any of your hypotheses, then, by design, you have to keep them in your model and fully report them as non-significant.</p>
</div>
</div>
<p>So we will leave out <code>mom_age_c</code> in our next model. The next model, therefore, add the final predictor variable in our dataset, <code>mom_hs_c</code>, the variable that describes whether a child’s mom complete their high school education. We will reuse the <code>m2_c</code> label for the model because we still only have two independent predictors here.</p>
<p><span class="math display">\[
model one: Kid\_score = Intercept + Mom's IQ + error
\]</span></p>
<p><span class="math display">\[
model two: Kid\_score = Intercept + Mom's IQ + Mom's HS status + error
\]</span></p>
<p>These two predictors are still independent of each other. We are hoping they will each predict a significant amount of <em>unique</em> variance on Children’s test scores. We can express this particular model with these two independent predictors like this</p>
<p><span class="math display">\[
Y = b_0 + b_1 * X_{mom\_iq} + b_2*X_{mom\_hs} + e
\]</span></p>
<p>Here is the code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2_c <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> mom_iq_c <span class="sc">+</span> mom_hs_c, d))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kid_score ~ 1 + mom_iq_c + mom_hs_c, data = d)

Residuals:
    Min      1Q  Median      3Q     Max 
-52.873 -12.663   2.404  11.356  49.545 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 86.79724    0.87054  99.705  &lt; 2e-16 ***
mom_iq_c     0.56391    0.06057   9.309  &lt; 2e-16 ***
mom_hs_c     5.95012    2.21181   2.690  0.00742 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.14 on 431 degrees of freedom
Multiple R-squared:  0.2141,    Adjusted R-squared:  0.2105 
F-statistic: 58.72 on 2 and 431 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>And as before, because I am building a series of models, I will perform my model comparison before interpreting the model. This is a time-saving measure, as you may not want to spend time interpreting a larger model if the change in variance explained for the model is not significantly different from the smaller model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1_c, m2_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: kid_score ~ 1 + mom_iq_c
Model 2: kid_score ~ 1 + mom_iq_c + mom_hs_c
  Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
1    432 144137                                
2    431 141757  1    2380.2 7.2369 0.007419 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>I will forego running through the layout of the table this time. Suffice to say that the line that begins with “2” is the line with the <em>p</em> value for the comparison. It is less than .05 so we can conclude that the change in the amount of variance explained between the two models is significant and the inclusion of the variable <code>mom_hs_c</code> is warranted. As we continue to build larger models, we should carry this verion of model <code>m2_c</code> forward.</p>
<p>So now we can interpret it - for practice. Let’s call the summary of model <code>m2_c</code> again to reduce the need for scrolling.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kid_score ~ 1 + mom_iq_c + mom_hs_c, data = d)

Residuals:
    Min      1Q  Median      3Q     Max 
-52.873 -12.663   2.404  11.356  49.545 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 86.79724    0.87054  99.705  &lt; 2e-16 ***
mom_iq_c     0.56391    0.06057   9.309  &lt; 2e-16 ***
mom_hs_c     5.95012    2.21181   2.690  0.00742 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.14 on 431 degrees of freedom
Multiple R-squared:  0.2141,    Adjusted R-squared:  0.2105 
F-statistic: 58.72 on 2 and 431 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The model is significant (<em>F</em>(2, 431) = 58.72, <em>p</em> &lt; .001) and the amount of variance explained for Children’s test scores is approximately 21%.</p>
<p>Mother’s IQ and children’s test scores are positively associated. A one unit increase in IQ is significantly associated with an increase in test scores of 0.56 test points (<em>t</em> = 9.31, <em>p</em> &lt; .001). Whether the child’s mother completed high school or not is also positively related to test scores. The difference in test scores for a child whose mother did not complete high school and a child whose mother did complete high school is 5.95 points (<em>t</em> = 2.69, <em>p</em> = .007).</p>
<p>If we run the mulitple regression model above, we may expect a plot of the regression to look something like this:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Images/Wk3/Ind_Mul_Regression.png" class="img-fluid figure-img"></p>
<figcaption>Regression with no interaction</figcaption>
</figure>
</div>
<p>I have put the raw data values on the X-axis for the best way to communicate the scale. I have also used the raw mom_hs factor here, again for simplicity. Remember that the transformations we performed do not change the information within the data. So this is okay.</p>
<p>As soon as we see a plot, lets take a moment to interpret it. What do we see:</p>
<ul>
<li>a scatterplot with two groups - signified by the two colours of black and grey dots
<ul>
<li>the legend shows black as 0 - the reference level here = mothers who did not complete high school</li>
<li>and grey as 1 = mothers who completed high school</li>
</ul></li>
<li>Mother’s IQ score on the X-axis is predicting Child Test Score on the Y-axis</li>
<li>The black line is lower than the grey line: the black line is for test scores of children whose mothers did not finish high school</li>
<li>The grey line is higher than the black line: the grey line is for test scores of children whose mothers did finish high school</li>
</ul>
<p>We know two pieces of information, from looking at this plot:</p>
<ol type="1">
<li><p>For all children, irrespective of whether their mom finished high school or not, as the mom’s IQ score increases, so does the child’s test score.</p></li>
<li><p>For children whose mothers finished high school, they get higher test scores than children whose mothers did not finish high school.</p></li>
</ol>
<p>Earlier, I said that these two predictors were independent of each other. We can see this in the plot because the effect for the difference in scores is constant across the range of IQ scores. The black and grey lines are parallel. And remain parallel across the span of the plot.</p>
</section>
<section id="a-multiple-regression-with-independent-predictors-and-an-interaction-term" class="level4">
<h4 class="anchored" data-anchor-id="a-multiple-regression-with-independent-predictors-and-an-interaction-term">A Multiple Regression with Independent Predictors and an Interaction Term</h4>
<p>What if we built a model that asked <code>mom_iq_c</code> and <code>mom_hs_c</code> to jointly predict some variance in the outcome variable. To do this, we need the variables to share their information with each other.</p>
<p>We are still only adding one predictor, and the smaller model will be nested inside the larger model. We are still using the same data.</p>
<p><span class="math display">\[
model two: Kid\_score = Intercept + Mom's IQ + Mom's HS status + error
\]</span></p>
<p><span class="math display">\[
model three: Kid\_score = Intercept + Mom's IQ + Mom's HS status + IQ * HS + error
\]</span></p>
<p>These two predictors are still in the model as independent predictors, but we also include a term where the two predictors look like they are multiplied together. This is what an interaction term is - the product of two or more variables added as an additional predictor in a model. Now we are hoping to see some <em>unique</em> variance from the independent predictors and also some joint prediction of variance from our interaction term. We can express the interaction model like this</p>
<p><span class="math display">\[
Y = b_0 + b_1 * X_{mom\_iq} + b_2*X_{mom\_hs} + b_3 * (X_{mom\_iq} * X_{mom\_hs}) + e
\]</span></p>
<p>Here is the code: I am calling it <code>m3_c_int</code> because it has 3 predictors, and contains an interaction term</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3_c_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> mom_iq_c <span class="sc">+</span> mom_hs_c <span class="sc">+</span> mom_iq_c<span class="sc">:</span>mom_hs_c, d))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kid_score ~ 1 + mom_iq_c + mom_hs_c + mom_iq_c:mom_hs_c, 
    data = d)

Residuals:
    Min      1Q  Median      3Q     Max 
-52.092 -11.332   2.066  11.663  43.880 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       87.63892    0.90756  96.565  &lt; 2e-16 ***
mom_iq_c           0.58839    0.06058   9.712  &lt; 2e-16 ***
mom_hs_c           2.84076    2.42667   1.171  0.24239    
mom_iq_c:mom_hs_c -0.48427    0.16222  -2.985  0.00299 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 17.97 on 430 degrees of freedom
Multiple R-squared:  0.2301,    Adjusted R-squared:  0.2247 
F-statistic: 42.84 on 3 and 430 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Before going any further, lets compare:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m2_c, m3_c_int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: kid_score ~ 1 + mom_iq_c + mom_hs_c
Model 2: kid_score ~ 1 + mom_iq_c + mom_hs_c + mom_iq_c:mom_hs_c
  Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
1    431 141757                                
2    430 138879  1    2878.4 8.9123 0.002994 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>My eyes have gone straight to the <em>p</em> value now: <em>p</em> = .003. It is smaller than .05 so we can conclude that the difference in the amount of variance explained in the outcome variable is significantly different in the larger model. The inclusion of the interaction term is warranted. If we were to build a larger model, then this larger model is the model that should be carried forward to the next step.</p>
<p>But we are not building any more models, as this dataset was a compact dataset and we have used up our variables.</p>
<p>When you come to the end of the line with model building in this incremental, step-wise fashion, you will interpret and present:</p>
<ul>
<li>the model that you hypothesised you would build</li>
<li>if there were several possible models from your hypotheses, you would present the one that was significantly the best predictor of variance.</li>
<li>Note - this may not be the model with the most variables!</li>
</ul>
<p>The model plot, with the addition of the interaction between mother’s IQ and high school education, looks like this:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Images/Wk3/Int_Mul_Regression.png" class="img-fluid figure-img"></p>
<figcaption>Regression with an interaction</figcaption>
</figure>
</div>
</section>
<section id="interpreting-a-model-with-an-interaction-term" class="level4">
<h4 class="anchored" data-anchor-id="interpreting-a-model-with-an-interaction-term">Interpreting a Model with an Interaction Term</h4>
<p>Up until now, we have been working with models of multiple independent predictors. Now we have a model with independent predictors and interaction terms. These take a little more interpretation. We will look at how to do that here.</p>
<p>When interpreting any interaction term, you will need:</p>
<ul>
<li>The regression coefficients for the independent predictors upon which the interaction term is based</li>
<li>The regression coefficient(s) for the interaction term.</li>
</ul>
<p>First of all, do a model summary inspection as you would with any other model: Is the model significant? How much variance in the outcome variable does the model explain? What does the intercept represent?</p>
<p>Then move on to the predictors. Interpret your independent predictors first. Our demonstration model is a very simple model. When you have models with more predictors, some of which may only be in the model as independent predictor, I suggest you look at those first before looking at the predictors that are involved in any interaction term.</p>
<p>When you are ready to interpret the interaction term, I suggest the following approach:</p>
<ol type="1">
<li>look at your first predictor and interpret it</li>
<li>look at the second predictor and intpret it</li>
<li>then look at the interaction term. Look at the sign of the regression coefficient first.
<ul>
<li>a positive coefficient suggests that at some point, the effect gets stronger than for the independent predictor</li>
<li>a negative coefficient suggests that at some point, the effect gets weaker than the independent predictor.</li>
</ul></li>
</ol>
<p>Lets do this for the <code>m3_c_int</code>. Lets call the summary here again to reduce the need for scrolling:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3_c_int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kid_score ~ 1 + mom_iq_c + mom_hs_c + mom_iq_c:mom_hs_c, 
    data = d)

Residuals:
    Min      1Q  Median      3Q     Max 
-52.092 -11.332   2.066  11.663  43.880 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       87.63892    0.90756  96.565  &lt; 2e-16 ***
mom_iq_c           0.58839    0.06058   9.712  &lt; 2e-16 ***
mom_hs_c           2.84076    2.42667   1.171  0.24239    
mom_iq_c:mom_hs_c -0.48427    0.16222  -2.985  0.00299 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 17.97 on 430 degrees of freedom
Multiple R-squared:  0.2301,    Adjusted R-squared:  0.2247 
F-statistic: 42.84 on 3 and 430 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><code>mom_iq_c</code> is significant; for a one point increase in IQ points, a child’s test scores increase by 0.58 points (<em>t</em> = 9.71, <em>p</em> &lt;.001). <code>mom_hs_c</code> is not significant. Notice that this is a change from the independent predictor model of <code>m2_c</code>. But we still need to understand what the coefficient suggests because we are going to interpret the interaction term. And this variable is also in the interaction term. This model predicts that for a mother who has completed high school, a child’s score increases by 2.84 points. The interaction term <code>mom_iq_c:mom_hs_c</code> is significant. It is negative. For one of the levels of high school completion, as IQ increases, that predicted 2.84 point increase for the independent predictor <code>mom_hs_c</code> is diminished or decreases by 0.48 points.</p>
<p>So lets now express this in plain(er) English:</p>
<p>As mom IQ increases, then a child’s test score increases and if mom completed high school, initially, those child test scores are stronger than test scores for children whos mom didn’t increase high school. But, and here is the impact of what the interaction coefficient is describing….that 2.84 initial advantage gets smaller and smaller (by about 0.48 point each time) with every increase in IQ.</p>
<p>To aid interpretation, look at the plot once more:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Images/Wk3/Int_Mul_Regression.png" class="img-fluid figure-img"></p>
<figcaption>Regression with an interaction</figcaption>
</figure>
</div>
<p>Interpret once more:</p>
<ul>
<li>Still a scatterplot using raw data with two groups - signified by the two colours of black and grey dots
<ul>
<li>the legend shows black as 0 - the reference level here and grey as 1</li>
<li>0 refers to mothers who did not finish high school in America</li>
<li>1 refers to mothers who did finish high school</li>
</ul></li>
<li>Still with Mother’s IQ score on the X-axis is predicting Child Test Score on the Y-axis</li>
<li>The two lines are still showing that advantage for the group whose mothers completed high school because the grey line is higher than the black line to begin with</li>
<li>but now, as we move from left to right across the plot, moving up the IQ scale, the grey line is not parallel to the black line.The grey line appears to be a shallower line - or have a slower rate of change - for every point increase in IQ, than the black line. This is the effect of losing 0.48 of a point as we increase in IQ.
<ul>
<li>The black line appears to be a steeper line - or have a faster rate of change - for every point increase in IQ than the grey line. This is because with every increase in IQ they are not feeling that loss of 0.48 of a point. It only applies to the group of children whose mothers completed high school.</li>
</ul></li>
</ul>
<p>The two pieces of information from the earlier plot, that we thought we knew have changed from looking at this plot:</p>
<ol type="1">
<li>The statement “For all children, irrespecitve of whether their mom finished high school or not, as the mom’s IQ score increases, so does the child’s test score” is still true but is not the entire interpretation. We now need to consider that the slopes are no longer parallel - they have different gradients…</li>
</ol>
<p>2a) The statement “For children whose mothers finished high school (grey line and dots), they get higher test scores than children whose mothers did not finish high school (black line and dots)” is only true for some of those children. And looking at the plot, I would say this is true for IQ levels that are lower than 100 (visual inspection of the plot). 2b) The inverse is true: “For children whose mothers finished high school (grey line and dots), they get lower test scores than children whose mothers did not finish high school (black line and dots)” is only true for some of those children. And looking at the plot, I would say this is true for IQ levels that are higher than 100 (visual inspection of the plot).</p>
<p>3a) We could add this: For children whose mothers did not finish high school (black line and dots), they get lower test scores than children whose mothers finished high school (grey line and dots) when the mom’s IQ level is lower than 100. 3b) For children whose mothers did not finish high school (black line and dots), they get higher test scores than children whose mothers finished high school (grey line and dots) when the mom’s IQ level higher than 100.</p>
<p>So the a child’s test score does not depend only on the mom’s IQ score or whether they finished their own education. Mom’s IQ score and high school education status interact with each other such that any child whose mom has an IQ scores higher than 100 is predicted to get a higher score than a child with a mom’s who has a lower than 100 IQ score, but for children in the group with mom’s who dropped out, the higher IQ scores seems to predict even higher scores than for those children whose mom finished their education.</p>
<p>This is the nature of an interaction. The effect of one predictor variable, or the rate of change or the size of the coefficient for one prediction variable may be different across the levels of a second predictor variable.</p>
<p>The two variables work together, rather than independently, on the outcome variable.</p>
<p>Lets look at the model summary that gave us this plot:</p>
<p>Lets do the math to show this numerically:</p>
<p>First look again at the high school variable</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d<span class="sc">$</span>mom_hs_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-0.7857  0.2143  0.2143  0.0000  0.2143  0.2143 </code></pre>
</div>
</div>
<p>Because this variable has been centred, the negative <code>Min</code> value represents the level of the variable for not finishing high school (-0.7857), the positive <code>Max</code> value represents the level of the variable for finishing high school (0.2143). You will put these values into some of the sums below.</p>
<p>The model says that at lower IQ scores, the children whose mum did finish high school have higher scores than children whose mum did not finish high school</p>
<p>Lets do the maths for 20 points below the average: We can model 80 IQ points as a prediction for lower IQ (modelled as -20 here as the sample average is 100 and 100 - 20 = 80)</p>
<p>Test score for a child with a mum who did not finish high school and an IQ of 80 (black line on the plot) Intercept + not_finishing high school + IQ 80 + Interaction term</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fl">87.63892</span> <span class="sc">+</span> (<span class="fl">0.58839</span><span class="sc">*-</span><span class="dv">20</span>) <span class="sc">+</span> (<span class="fl">2.84076</span><span class="sc">*-</span><span class="fl">0.7857</span>) <span class="sc">+</span> <span class="sc">-</span><span class="fl">0.48427</span><span class="sc">*</span>(<span class="sc">-</span><span class="fl">0.7857</span><span class="sc">*-</span><span class="dv">20</span>) <span class="co"># -0.7857 = represents mothers who did not finish high school</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 66.02932</code></pre>
</div>
</div>
<p>Test score for a child with a mum who did finish high school and an IQ of 80 (grey line on the plot) Intercept + not_finishing high school + IQ 80 + Interaction term</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fl">87.63892</span> <span class="sc">+</span>  (<span class="fl">0.58839</span><span class="sc">*-</span><span class="dv">20</span>) <span class="sc">+</span> (<span class="fl">2.84076</span><span class="sc">*</span><span class="fl">0.2143</span>) <span class="sc">+</span> <span class="sc">-</span><span class="fl">0.48427</span><span class="sc">*</span>(<span class="fl">0.2143</span><span class="sc">*-</span><span class="dv">20</span>) <span class="co"># 0.2143 = represents mothers who did finish high school</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 78.55548</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>(<span class="fl">78.55548</span> <span class="sc">-</span> <span class="fl">66.02932</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.52616</code></pre>
</div>
</div>
<p>As the model predicts, the advantage is for the children whos mothers did finish high school. The size of the advantage, when mums IQ is at 80, is approximately 12.5 points.</p>
<p>Lets look at what the scores are like for an IQ of 81…we should see a difference of 12.52616-0.48…the size of the advantage has gotten smaller by about 0.48 points</p>
<p>IQ is now -19 (because 100-19 = 81)</p>
<p>Test score for a child with a mum who did not finish high school and an IQ of 81 (black line on the plot) Intercept + not_finishing high school + IQ 81 + Interaction term</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fl">87.63892</span> <span class="sc">+</span> (<span class="fl">0.58839</span><span class="sc">*-</span><span class="dv">19</span>) <span class="sc">+</span> (<span class="fl">2.84076</span><span class="sc">*-</span><span class="fl">0.7857</span>) <span class="sc">+</span> <span class="sc">-</span><span class="fl">0.48427</span><span class="sc">*</span>(<span class="sc">-</span><span class="fl">0.7857</span><span class="sc">*-</span><span class="dv">19</span>) <span class="co"># -0.7857 = represents mothers who did not finish high school</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 66.9982</code></pre>
</div>
</div>
<p>Test score for a child with a mum who did finish high school and an IQ of 81 (grey line on the plot) Intercept + not_finishing high school + IQ 81 + Interaction term</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fl">87.63892</span> <span class="sc">+</span> (<span class="fl">0.58839</span><span class="sc">*-</span><span class="dv">19</span>) <span class="sc">+</span> (<span class="fl">2.84076</span><span class="sc">*</span><span class="fl">0.2143</span>) <span class="sc">+</span> <span class="sc">-</span><span class="fl">0.48427</span><span class="sc">*</span>(<span class="fl">0.2143</span><span class="sc">*-</span><span class="dv">19</span>) <span class="co"># 0.2143 = represents mothers who did finish high school</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 79.04009</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># point difference between groups</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>(<span class="fl">79.04009</span> <span class="sc">-</span>  <span class="fl">66.9982</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.04189</code></pre>
</div>
</div>
<p>the point score difference at 80 IQ points, is 12.53, the point score difference at 81 IQ points is 12.04</p>
<p>If we take 12.52616 from 12.04189, we get:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>(<span class="fl">12.04189-12.52616</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.48427</code></pre>
</div>
</div>
<p>Which is the negative regression coefficient for the interaction term. As we increase the IQ points from 80 to 81, the difference in scores decreases between the groups by about half a point.</p>
<p>Lets look at the size of the gap at the sample IQ points of 101: if you look back at the plot, the lines are almost meeting at this point, any advantage that any group has will be much smaller.</p>
<p>IQ is now expressed in this sum as 1, because the IQ variable in the model is centred at the sample average for IQ which is 100. So and IQ of 101 = +1</p>
<p>Finding the Test score for a child with a mum who did not finish high school and an IQ of 101 (black line on the plot) Intercept + not_finishing high school + IQ 101 + Interaction term</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fl">87.63892</span> <span class="sc">+</span> (<span class="fl">0.58839</span><span class="sc">*</span><span class="dv">1</span>) <span class="sc">+</span> (<span class="fl">2.84076</span><span class="sc">*-</span><span class="fl">0.7857</span>) <span class="sc">+</span> <span class="sc">-</span><span class="fl">0.48427</span><span class="sc">*</span>(<span class="sc">-</span><span class="fl">0.7857</span><span class="sc">*</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 86.37582</code></pre>
</div>
</div>
<p>Test score for a child with a mum who did finish high school and an IQ of 101 (grey line on the plot) Intercept + not_finishing high school + IQ 101 + Interaction term</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fl">87.63892</span> <span class="sc">+</span> (<span class="fl">0.58839</span><span class="sc">*</span><span class="dv">1</span>) <span class="sc">+</span> (<span class="fl">2.84076</span><span class="sc">*</span><span class="fl">0.2143</span>) <span class="sc">+</span> <span class="sc">-</span><span class="fl">0.48427</span><span class="sc">*</span>(<span class="fl">0.2143</span><span class="sc">*</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 88.73231</code></pre>
</div>
</div>
<p>The difference at IQ 101 is much smaller than at IQ 81, but there does still seem to be a slight advantage for the group whose mum finished high school.</p>
<p>And once more Lets move the IQ a bit higher: to 120</p>
<p>Test score for a child with a mum who did not finish high school and an IQ of 120 (black line on the plot) Intercept + not_finishing high school + IQ 120 + Interaction term</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fl">87.63892</span> <span class="sc">+</span> (<span class="fl">0.58839</span><span class="sc">*</span><span class="dv">20</span>) <span class="sc">+</span> (<span class="fl">2.84076</span><span class="sc">*-</span><span class="fl">0.7857</span>) <span class="sc">+</span> <span class="sc">-</span><span class="fl">0.48427</span><span class="sc">*</span>(<span class="sc">-</span><span class="fl">0.7857</span><span class="sc">*</span><span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 104.7846</code></pre>
</div>
</div>
<p>Test score for a child with a mum who did finish high school and an IQ of 120 (grey line on the plot) Intercept + not_finishing high school + IQ 120 + Interaction term</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fl">87.63892</span> <span class="sc">+</span> (<span class="fl">0.58839</span><span class="sc">*</span><span class="dv">20</span>) <span class="sc">+</span> (<span class="fl">2.84076</span><span class="sc">*</span><span class="fl">0.2143</span>) <span class="sc">+</span> <span class="sc">-</span><span class="fl">0.48427</span><span class="sc">*</span>(<span class="fl">0.2143</span><span class="sc">*</span><span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 97.93991</code></pre>
</div>
</div>
<p>At IQ of 101, the children with mothers who had finished high school were slightly higher than children whose mothers had not finished high school, but the effect of that advantage has decreased as IQ increased. At IQ 120, the group whose mum did not finish high school (black line) are now showing a score advantage over the group whose mum did finish high school with the difference being approximately 7 points between the two groups).</p>
</section>
</section>
<section id="model-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="model-diagnostics">Model diagnostics</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)) <span class="co"># display plots in a 2 x 2 panel</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m3_c_int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week3_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This model looks pretty healthy on the residuals!</p>
</section>
<section id="communicate" class="level3">
<h3 class="anchored" data-anchor-id="communicate">Communicate</h3>
<p>A sample text for communicating this model:</p>
<p>We ran a multiple regression model to predict children’s test scores at age 3-years, from mother’s IQ score, whether they had completed high school or not and the interaction between the two. We centred the predictors before putting them into the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3_c_int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kid_score ~ 1 + mom_iq_c + mom_hs_c + mom_iq_c:mom_hs_c, 
    data = d)

Residuals:
    Min      1Q  Median      3Q     Max 
-52.092 -11.332   2.066  11.663  43.880 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       87.63892    0.90756  96.565  &lt; 2e-16 ***
mom_iq_c           0.58839    0.06058   9.712  &lt; 2e-16 ***
mom_hs_c           2.84076    2.42667   1.171  0.24239    
mom_iq_c:mom_hs_c -0.48427    0.16222  -2.985  0.00299 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 17.97 on 430 degrees of freedom
Multiple R-squared:  0.2301,    Adjusted R-squared:  0.2247 
F-statistic: 42.84 on 3 and 430 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The model was significant (<em>F</em>(3, 430) = 42.84, <em>p</em> &lt; .001) and explained 23% of the variance in the children’s test scores. Mother’s IQ is positively related to children’s test scores, with each increase in IQ, test scores increased by 0.58 of a point (<em>t</em> = 9.71, <em>p</em> &lt; .001). The predictor for whether or not a mother had completed their high school education was not significant (<em>b</em> = 2.84, <em>t</em> = 1.17, <em>p</em> = 0.242) however the interaction term for mother’s IQ and education status was significant (<em>b</em> = -0.48, <em>t</em> = -2.99, <em>p</em> = .003). This indicates that while the test scores for children whose mothers completed high school show an initial advantage of 2.84 points, this advantage decreases with each increase of an IQ point by 0.48 of a test point. Indeed, Figure 1 shows that at the higher levels of IQ in this sample, the group of children whose mothers did not finish high school, have higher test scores than those children whose mothers did finish high school.</p>
</section>
<section id="what-are-interaction-terms" class="level3">
<h3 class="anchored" data-anchor-id="what-are-interaction-terms">What are interaction terms?</h3>
<ul>
<li>We interpret each predictor as representing a value of the variable’s influence on the outcome variable while holding all other predictors constant</li>
<li>The coefficient for each predictor tells us how the outcome variable increases or decreases over incremental increases of a predictor - a constant rate of change…adding one unit each time, increases or decreases the outcome variable by the values of the coefficient</li>
</ul>
<p>Interactions are the product term of two (or more) predictors. There are several ways to create them:</p>
<ul>
<li>We can do a maths sum: multiply two (or more) variables together and save them to your dataset then call that predictor in your model</li>
<li>You can use R code to write the interaction term into your model (so it is not a physical varaible in your dataset)
<ul>
<li>we did this in model <code>m3_c_int</code>.</li>
</ul></li>
</ul>
<p>Putting it into your model formula can be expressed in two ways. There is the use of a colon (:) as here:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>m3_c_int_colon <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> mom_iq_c <span class="sc">+</span> mom_hs_c <span class="sc">+</span> mom_iq_c<span class="sc">:</span>mom_hs_c, d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Or, an equivalent model to <code>m3_c_int</code> is expressed using a shorter form of code, using an asterisk (*)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>m3_c_int_Asterisk <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> mom_iq_c<span class="sc">*</span>mom_hs_c, d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>both of these types of model code give the exact same model output:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3_c_int_colon)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kid_score ~ 1 + mom_iq_c + mom_hs_c + mom_iq_c:mom_hs_c, 
    data = d)

Residuals:
    Min      1Q  Median      3Q     Max 
-52.092 -11.332   2.066  11.663  43.880 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       87.63892    0.90756  96.565  &lt; 2e-16 ***
mom_iq_c           0.58839    0.06058   9.712  &lt; 2e-16 ***
mom_hs_c           2.84076    2.42667   1.171  0.24239    
mom_iq_c:mom_hs_c -0.48427    0.16222  -2.985  0.00299 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 17.97 on 430 degrees of freedom
Multiple R-squared:  0.2301,    Adjusted R-squared:  0.2247 
F-statistic: 42.84 on 3 and 430 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3_c_int_Asterisk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kid_score ~ 1 + mom_iq_c * mom_hs_c, data = d)

Residuals:
    Min      1Q  Median      3Q     Max 
-52.092 -11.332   2.066  11.663  43.880 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       87.63892    0.90756  96.565  &lt; 2e-16 ***
mom_iq_c           0.58839    0.06058   9.712  &lt; 2e-16 ***
mom_hs_c           2.84076    2.42667   1.171  0.24239    
mom_iq_c:mom_hs_c -0.48427    0.16222  -2.985  0.00299 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 17.97 on 430 degrees of freedom
Multiple R-squared:  0.2301,    Adjusted R-squared:  0.2247 
F-statistic: 42.84 on 3 and 430 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="when-are-interaction-terms-used" class="level3">
<h3 class="anchored" data-anchor-id="when-are-interaction-terms-used">When are interaction terms used?</h3>
<ul>
<li>Theory may predict them, and so research questions/hypotheses may predict them.</li>
<li>Study design may implicitly suggest them (groups?)</li>
<li>Results may suggest them
<ul>
<li>Regression coefficients that seem large when modelled independently may suggest the need for an interaction term</li>
</ul></li>
</ul>
</section>
<section id="statistical-power-of-interactions" class="level3">
<h3 class="anchored" data-anchor-id="statistical-power-of-interactions">Statistical Power of Interactions</h3>
<p>Many effect sizes for independent predictors (or main effects in ANOVA language) in psychology hover around Cohen’s <em>d</em> = 0.4</p>
<p>Based upon an effect size like this:</p>
<ul>
<li>The power of an interaction can be a small as 1/16th of the independent effects within a model (Gelman et al.&nbsp;2020)</li>
<li>This is for ANOVA and regression methods</li>
<li>This is when all the assumptions of the model are met
<ul>
<li>Most models violate model assumptions in some way</li>
<li>Although relatively tolerant of violations: Power of the effects are thus reduced further…</li>
</ul></li>
</ul>
</section>
<section id="preparation-of-data-for-using-interactions" class="level3">
<h3 class="anchored" data-anchor-id="preparation-of-data-for-using-interactions">Preparation of data for using interactions</h3>
<p>Centre or standardise your continuous variables as standardising puts both predictors on the same scale. So interpreting the effect of one predictor on the other will be using the same scale of units</p>
<p>Consider how to use your categorical variables: - Dummy coding..? - Sum coding..? - Making new binary variables…? - Coercing a binary variable to numeric class and mean centring</p>
</section>
<section id="building-a-model-with-interactions" class="level3">
<h3 class="anchored" data-anchor-id="building-a-model-with-interactions">Building a model with interactions</h3>
<p>Plan to build the model suggested by your research questions/hypotheses/theory. If that includes the interaction term, build it as the first model. If not, build an independent predictor model first and then build a further model that includes independent and interaction terms. Perform a model comparison as above to see if your interaction term has given you more explained variance at a significant level.</p>
<p>How are we doing in our list of things to think about - We need to look at:</p>
<ul>
<li>a model with some significant predictors! - done</li>
<li>correlation matrices - done</li>
<li>centering predictors - done</li>
<li>standardising predictors - done</li>
<li>models with categorical predictors - done &amp; ongoing
<ul>
<li>interpreting models with categorical predictors - done &amp; ongoing</li>
</ul></li>
<li>models with interaction terms - done</li>
<li>the properties of multicollinearity - week 15</li>
<li>choosing between different models - done &amp; ongoing</li>
<li>reporting models - ongoing</li>
</ul>
</section>
</section>
<section id="model-script" class="level2">
<h2 class="anchored" data-anchor-id="model-script">Model script</h2>
<p>A model script showing one way of answering the research questions above using R will be available next week.</p>


</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../PSYC234/Week2.html" class="pagination-link" aria-label="2. Multiple Regression Including Categorical Predictors">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">2. Multiple Regression Including Categorical Predictors</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../PSYC234/Week4.html" class="pagination-link" aria-label="4. Mediation">
        <span class="nav-page-text">4. Mediation</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Website developed by Matthew Ivory</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../previous-content/index.html">
<p>Previous Content</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>